// Optional browser suite; supply an existing Playwright installation, no Sheet access.
const {chromium}=await import(process.env.PLAYWRIGHT_MODULE||'playwright');
import {mkdir} from 'node:fs/promises';
const appUrl=process.env.LEDGER_TEST_URL||'http://127.0.0.1:5175';
const artifacts=process.env.LEDGER_TEST_ARTIFACTS||'/tmp/ledger-browser-results';
await mkdir(artifacts,{recursive:true});
import assert from 'node:assert/strict';
import {accountBackend} from '../helpers/accountBackend.js';
const browser=await chromium.launch({headless:true,args:['--no-sandbox']});
const context=await browser.newContext({viewport:{width:1440,height:1000},serviceWorkers:'block'});
const page=await context.newPage();page.setDefaultTimeout(6000);
const backend=accountBackend(),errors=[],calls=[];let gate=null,failNetwork=false,failWrite=false,failPartyWrite=false,loseReply=false,legacyReplies=false,readGate=null;
page.on('pageerror',error=>errors.push(error.message));
page.on('dialog',dialog=>dialog.accept());
await context.addInitScript(()=>{if(!localStorage.getItem('rf.endpoint')){const endpoint='https://script.google.com/macros/s/TEST-ONLY/exec';localStorage.setItem('rf.endpoint',JSON.stringify(endpoint));localStorage.setItem('rf.connectionInfo',JSON.stringify({endpoint,version:'1.8.1'}));}});
await context.route('https://script.google.com/**',async route=>{
 const body=route.request().postDataJSON();calls.push(body?.action||'list');
 if(failNetwork&&body&&['createParty','createInvoice'].includes(body.action)){await route.abort('failed');return;}
 if(gate&&body?.action==='createParty')await gate;
 if(failPartyWrite&&body?.action==='createParty'){failPartyWrite=false;await route.fulfill({json:{ok:false,code:'REQUEST_FAILED',error:'Simulated party rejection',backendVersion:'1.8.1'}});return;}
 if(loseReply&&body?.action==='createInvoice'){loseReply=false;backend.post(body.action,body.transaction);await route.abort('failed');return;}
 if(failWrite&&body?.action==='createInvoice'){failWrite=false;await route.fulfill({json:{ok:false,code:'REQUEST_FAILED',error:'Simulated validation rejection',backendVersion:'1.8.1'}});return;}
 const result=body?backend.post(body.action,body.transaction):backend.context.doGet();if(readGate&&body?.action==='listAccounts')await readGate;if(legacyReplies&&body&&result.record)delete result.record;await route.fulfill({json:result});
});
const dialog=()=>page.locator('.account-invoice-dialog');
const form=()=>page.locator('.invoice-form');
const openNew=async()=>{await page.locator('.dashboard-actions').getByRole('button',{name:/New Invoice \/ Note/}).click();await dialog().waitFor();};
const closePopup=async()=>{await page.locator('dialog[open]').getByRole('button',{name:'Close popup'}).click();};
const queueLength=()=>page.evaluate(()=>JSON.parse(localStorage.getItem('rf.accounts.pending')||'{"queue":[]}').queue.length);
try{
 await page.goto(appUrl);
 await page.locator('.dashboard-actions button').nth(1).waitFor({state:'visible'});
 await page.waitForFunction(()=>!document.querySelector('.dashboard-actions button:nth-child(2)').disabled);
 await openNew();assert.equal(await page.locator('[role=listbox]').count(),0);
 await form().getByLabel('Item 1 description').fill('Sofa');const nameField=form().getByLabel('Item 1 description');await nameField.press('Home');await nameField.press('ArrowRight');await nameField.press('a');await nameField.press('b');assert.equal(await nameField.inputValue(),'SABOFA');await nameField.fill('Sofa');await form().getByLabel('Rate (₹)',{exact:true}).fill('2000');
 assert.match(await page.locator('.invoice-submit-total').innerText(),/2,000/);
 // Resume preserves invoice items and a typed, unselected party across close/reload.
 await form().getByRole('combobox',{name:/Party/}).fill('Draft customer');await closePopup();await page.locator('.dashboard-actions').getByRole('button',{name:'Resume draft',exact:true}).click();await dialog().waitFor();assert.equal(await form().getByLabel('Item 1 description').inputValue(),'SOFA');assert.equal(await form().getByRole('combobox',{name:/Party/}).inputValue(),'Draft customer');await closePopup();await page.reload();await page.waitForFunction(()=>!Array.from(document.querySelectorAll('.dashboard-actions button')).find(button=>button.textContent==='Resume draft')?.disabled);await page.locator('.dashboard-actions').getByRole('button',{name:'Resume draft',exact:true}).click();await dialog().waitFor();assert.equal(await form().getByLabel('Item 1 description').inputValue(),'SOFA');assert.equal(await form().getByRole('combobox',{name:/Party/}).inputValue(),'Draft customer');
 await form().getByRole('combobox',{name:/Party/}).fill('Unique Alpha');await form().getByRole('combobox',{name:/Party/}).press('Enter');
 await page.getByRole('heading',{name:'New party',exact:true}).waitFor();
 assert.equal(await page.getByLabel('Name',{exact:true}).inputValue(),'Unique Alpha');
 assert.equal(await page.locator('dialog[open]').count(),1);assert.equal(await page.locator('.account-party-dialog .party-form').count(),1);assert.equal(await page.getByLabel('Name',{exact:true}).evaluate(element=>element===document.activeElement),true);
 await page.getByLabel('Name',{exact:true}).press('Escape');await dialog().waitFor();assert.equal(await form().getByLabel('Item 1 description').inputValue(),'SOFA');await form().getByRole('combobox',{name:/Party/}).press('Enter');await page.locator('.account-party-dialog').waitFor();

 await page.getByRole('button',{name:'Back to invoice',exact:true}).click();await dialog().waitFor();assert.equal(await form().getByLabel('Item 1 description').inputValue(),'SOFA');
 await form().getByRole('combobox',{name:/Party/}).press('Enter');await page.getByRole('heading',{name:'New party',exact:true}).waitFor();
 let release;gate=new Promise(resolve=>release=resolve);
 const t0=Date.now();await page.locator('.account-form').evaluate(form=>{form.requestSubmit();form.requestSubmit();});await dialog().waitFor();const partyLatency=Date.now()-t0;
 assert.ok(partyLatency<1000,`party return took ${partyLatency}ms`);assert.equal(await form().getByRole('combobox',{name:/Party/}).inputValue(),'Unique Alpha');
 assert.equal(await page.locator('[role=listbox]').count(),0);
 await form().getByLabel('Cost price (₹)').fill('1400');await form().getByLabel('Challan No.').fill('DC-100');
 const t1=Date.now();await form().evaluate(form=>{form.requestSubmit();form.requestSubmit();});await page.locator('dialog[open] .invoice-document').waitFor();const invoiceLatency=Date.now()-t1;
 assert.ok(invoiceLatency<1000,`invoice preview took ${invoiceLatency}ms`);assert.match(await page.locator('.invoice-document').innerText(),/Unique Alpha/);assert.equal(await queueLength(),2);
 assert.equal(await page.locator('dialog[open] .record-menu button').filter({hasText:'Print Invoice'}).isDisabled(),true);
 const readsBefore=calls.filter(action=>action==='listAccounts').length;
 gate=null;release();await page.waitForFunction(()=>!localStorage.getItem('rf.accounts.pending'));
 assert.match(await page.locator('.invoice-document').innerText(),/RF-S-000001/);assert.equal(backend.post('listAccounts',{}).parties.length,1);assert.equal(backend.post('listAccounts',{}).invoices.length,1);
 assert.equal(calls.filter(action=>action==='listAccounts').length,readsBefore,'successful writes should not fetch every sheet again');
 await closePopup();await openNew();assert.equal(await form().getByRole('combobox',{name:/Party/}).inputValue(),'');assert.equal(await form().getByLabel('Item 1 description').inputValue(),'');
 await form().getByRole('combobox',{name:/Party/}).fill('Uni');await form().getByRole('combobox',{name:/Party/}).press('Enter');assert.equal(await form().getByRole('combobox',{name:/Party/}).inputValue(),'Unique Alpha');
 await form().getByLabel('Item 1 description').fill('Chair');await form().getByLabel('Rate (₹)',{exact:true}).fill('100');
 await form().getByRole('button',{name:/Add item/}).click();await page.waitForFunction(()=>document.activeElement?.getAttribute('aria-label')==='Item 2 description');
 await form().getByRole('button',{name:'Remove',exact:true}).last().click();
 await form().getByRole('group',{name:'Document type'}).getByRole('button',{name:/Purchase invoice/}).click();await form().getByRole('button',{name:/Issue invoice/}).click();await page.locator('dialog[open] .invoice-document').waitFor();
 await page.waitForFunction(()=>!localStorage.getItem('rf.accounts.pending'));assert.match(await page.locator('.invoice-document').innerText(),/RF-P-000001/);
 await closePopup();
 // Network interruption, durable restart and retry.
 failNetwork=true;await openNew();await form().getByRole('combobox',{name:/Party/}).fill('Uni');await form().getByRole('combobox',{name:/Party/}).press('Enter');await form().getByLabel('Item 1 description').fill('Offline item');await form().getByLabel('Rate (₹)',{exact:true}).fill('42');
 await form().getByRole('button',{name:/Issue invoice/}).click();await page.waitForFunction(()=>JSON.parse(localStorage.getItem('rf.accounts.pending'))?.queue?.[0]?.failure);
 await page.reload();await page.getByRole('button',{name:'Retry upload',exact:true}).waitFor();assert.equal(await queueLength(),1);
 failNetwork=false;await page.getByRole('button',{name:'Retry upload',exact:true}).click();await page.waitForFunction(()=>!localStorage.getItem('rf.accounts.pending'));
 assert.equal(backend.post('listAccounts',{}).invoices.length,3);
 // Backend rejection restores one editable draft rather than stacking two dialogs.
 failWrite=true;await openNew();await form().getByRole('combobox',{name:/Party/}).fill('Uni');await form().getByRole('combobox',{name:/Party/}).press('Enter');await form().getByLabel('Item 1 description').fill('Rejected item');await form().getByLabel('Rate (₹)',{exact:true}).fill('90');await form().getByRole('button',{name:/Issue invoice/}).click();
 await page.getByRole('button',{name:'Review rejected upload',exact:true}).waitFor();await closePopup();await page.getByRole('button',{name:'Review rejected upload',exact:true}).click();await page.getByRole('button',{name:'Discard rejected request',exact:true}).click();await dialog().waitFor();assert.equal(await page.locator('dialog[open]').count(),1);assert.equal(await form().getByLabel('Item 1 description').inputValue(),'REJECTED ITEM');
 await form().getByRole('button',{name:/Issue invoice/}).click();await page.locator('dialog[open] .invoice-document').waitFor();await page.waitForFunction(()=>!localStorage.getItem('rf.accounts.pending'));await closePopup();
 // Local storage quota: keep the form and do not send an unrecorded invoice.
 await openNew();await form().getByRole('combobox',{name:/Party/}).fill('Uni');await form().getByRole('combobox',{name:/Party/}).press('Enter');await form().getByLabel('Item 1 description').fill('Quota item');await form().getByLabel('Rate (₹)',{exact:true}).fill('91');
 await page.evaluate(()=>{window.originalSetItem=Storage.prototype.setItem;Storage.prototype.setItem=function(key,value){if(key==='rf.accounts.pending')throw new DOMException('Quota exceeded','QuotaExceededError');return window.originalSetItem.call(this,key,value);};});
 const countBeforeQuota=calls.filter(action=>action==='createInvoice').length;await form().getByRole('button',{name:/Issue invoice/}).click();await dialog().getByRole('alert').waitFor();assert.equal(await form().getByLabel('Item 1 description').inputValue(),'QUOTA ITEM');assert.equal(calls.filter(action=>action==='createInvoice').length,countBeforeQuota);await page.evaluate(()=>{Storage.prototype.setItem=window.originalSetItem;});
 // Invalid discount and zero quantity never enqueue a request.
 await form().getByLabel('Line discount (₹)').fill('92');await form().getByRole('button',{name:/Issue invoice/}).click();assert.match(await dialog().getByRole('alert').innerText(),/discount/);assert.equal(await queueLength(),0);
 await form().getByLabel('Line discount (₹)').fill('0');await form().getByLabel('Quantity',{exact:true}).fill('0');await form().getByRole('button',{name:/Issue invoice/}).click();assert.equal(await queueLength(),0);await form().getByLabel('Quantity',{exact:true}).fill('1');
 // A committed invoice with a lost response retries its original ID/number.
 loseReply=true;await form().getByRole('button',{name:/Issue invoice/}).click();await page.waitForFunction(()=>JSON.parse(localStorage.getItem('rf.accounts.pending'))?.queue?.[0]?.failure);const invoicesBeforeRetry=backend.post('listAccounts',{}).invoices.length;await closePopup();await page.getByRole('button',{name:'Retry upload',exact:true}).click();await page.waitForFunction(()=>!localStorage.getItem('rf.accounts.pending'));assert.equal(backend.post('listAccounts',{}).invoices.length,invoicesBeforeRetry);
 // Direct party creation and editing still return to the detail page.
 await page.locator('.sidebar').getByRole('button',{name:/Parties/}).click();await page.getByRole('button',{name:/Add Party/}).click();await page.locator('.account-party-dialog').waitFor();await closePopup();assert.equal(await page.evaluate(()=>document.body.style.overflow),'');await page.getByRole('button',{name:/Add Party/}).click();await page.getByLabel('Name',{exact:true}).fill('   ');await page.getByRole('button',{name:'Save party',exact:true}).click();await page.locator('.account-party-dialog').getByRole('alert').filter({hasText:'Enter a party name'}).waitFor();await page.getByLabel('Name',{exact:true}).fill('Direct party');await page.getByLabel('Phone',{exact:true}).fill('123456789');await page.getByLabel('Opening amount (₹)').fill('10');await page.getByRole('button',{name:'Save party',exact:true}).click();await page.getByRole('heading',{name:'Direct party',exact:true}).waitFor();await page.getByRole('button',{name:'Edit contact details',exact:true}).click();await page.locator('.account-party-dialog').getByRole('heading',{name:'Edit party contact details',exact:true}).waitFor();await page.getByLabel('Phone',{exact:true}).fill('555555555');await closePopup();assert.match(await page.locator('.party-contact-details').innerText(),/123456789/);await page.getByRole('button',{name:'Edit contact details',exact:true}).click();assert.equal(await page.getByLabel('Phone',{exact:true}).inputValue(),'123456789');await page.getByLabel('Phone',{exact:true}).fill('999999999');await page.getByRole('button',{name:'Save party',exact:true}).click();await page.waitForFunction(()=>!document.querySelector('.account-form'));assert.match(await page.locator('.party-contact-details').innerText(),/999999999/);
 await page.getByRole('button',{name:'New Invoice / Note',exact:true}).click();await dialog().waitFor();assert.equal(await form().getByRole('combobox',{name:/Party/}).inputValue(),'Direct party');assert.equal(await form().getByLabel('Item 1 description').inputValue(),'');await closePopup();await page.locator('.sidebar').getByRole('button',{name:/Dashboard/}).click();
 // Search includes settled/payable accounts regardless of the selected balance tab.
 for(const [id,name,phone,balance] of [['party-000000000000000010','Settled customer','777777777',0],['party-000000000000000011','Payable customer','888888888',-3000]])assert.equal(backend.post('createParty',{id,schemaVersion:1,name,phone,address:'',openingDate:'2026-01-01',openingBalanceMinor:balance}).ok,true);
 await page.locator('.period-bar .refresh').click();await page.waitForFunction(()=>!document.querySelector('.accounts-view .help')?.textContent?.includes('Updating balances'));await page.locator('.sidebar').getByRole('button',{name:/Parties/}).click();await page.getByRole('button',{name:'← Back to parties',exact:true}).click();await page.getByRole('searchbox',{name:'Search all parties'}).fill('777777');await page.locator('.party-balance-row').filter({hasText:'Settled customer'}).waitFor();assert.match(await page.locator('.party-balance-row').innerText(),/Settled/);await page.locator('.party-balance-row').click();assert.match(await page.locator('.party-total').innerText(),/Settled/);await page.getByRole('button',{name:'← Back to parties',exact:true}).click();await page.getByRole('searchbox',{name:'Search all parties'}).fill('Payable');assert.match(await page.locator('.party-balance-row').innerText(),/To Pay/);await page.getByRole('searchbox',{name:'Search all parties'}).fill('Does not exist');await page.getByText('No parties match this search.',{exact:true}).waitFor();await page.getByRole('button',{name:'Clear search',exact:true}).click();assert.equal(await page.locator('.party-balance-row').filter({hasText:'Settled customer'}).count(),0);await page.locator('.sidebar').getByRole('button',{name:/Dashboard/}).click();
 // Two tabs enqueue concurrently while one party write is blocked.
 let releaseTabs;gate=new Promise(resolve=>releaseTabs=resolve);await openNew();await form().getByRole('combobox',{name:/Party/}).fill('Parallel party');await form().getByRole('combobox',{name:/Party/}).press('Enter');await page.getByRole('button',{name:'Save party',exact:true}).click();await dialog().waitFor();await form().getByLabel('Item 1 description').fill('Tab one');await form().getByLabel('Rate (₹)',{exact:true}).fill('10');await form().getByRole('button',{name:/Issue invoice/}).click();await closePopup();
 const second=await context.newPage();second.on('pageerror',error=>errors.push(error.message));second.on('dialog',d=>d.accept());await second.goto(appUrl);await second.waitForFunction(()=>!document.querySelector('.dashboard-actions button:nth-child(2)').disabled);await second.locator('.dashboard-actions').getByRole('button',{name:/New Invoice \/ Note/}).click();const secondForm=second.locator('.invoice-form');await secondForm.getByRole('combobox',{name:/Party/}).fill('Uni');await secondForm.getByRole('combobox',{name:/Party/}).press('Enter');await secondForm.getByLabel('Item 1 description').fill('Tab two');await secondForm.getByLabel('Rate (₹)',{exact:true}).fill('11');await secondForm.getByRole('button',{name:/Issue invoice/}).click();await page.waitForFunction(()=>JSON.parse(localStorage.getItem('rf.accounts.pending'))?.queue?.length===3);assert.equal(await queueLength(),3);gate=null;releaseTabs();await page.waitForFunction(()=>!localStorage.getItem('rf.accounts.pending'));await second.waitForFunction(()=>!localStorage.getItem('rf.accounts.pending'));assert.equal(backend.post('listAccounts',{}).invoices.length,invoicesBeforeRetry+2);await second.close();
 // A rejected party keeps dependent invoices and permits correcting that same ID.
 let releaseRejected;gate=new Promise(resolve=>releaseRejected=resolve);failPartyWrite=true;await openNew();await form().getByRole('combobox',{name:/Party/}).fill('Rejected party');await form().getByRole('combobox',{name:/Party/}).press('Enter');await page.getByRole('button',{name:'Save party',exact:true}).click();await dialog().waitFor();await form().getByLabel('Item 1 description').fill('Dependent item');await form().getByLabel('Rate (₹)',{exact:true}).fill('12');await form().getByRole('button',{name:/Issue invoice/}).click();await page.waitForFunction(()=>JSON.parse(localStorage.getItem('rf.accounts.pending'))?.queue?.length===2);gate=null;releaseRejected();await page.getByRole('button',{name:'Review rejected upload',exact:true}).waitFor();await closePopup();await page.getByRole('button',{name:'Review rejected upload',exact:true}).click();await page.getByRole('button',{name:'Discard rejected request',exact:true}).click();await page.getByRole('alert').filter({hasText:'An invoice is waiting'}).waitFor();assert.equal(await queueLength(),2);await page.getByRole('button',{name:'Correct rejected party',exact:true}).click();await page.getByLabel('Name',{exact:true}).fill('Corrected party');await page.getByRole('button',{name:'Save party',exact:true}).click();await page.waitForFunction(()=>!localStorage.getItem('rf.accounts.pending'));assert.equal(backend.post('listAccounts',{}).invoices.at(-1).partyName,'Corrected party');
 // Printing refreshes confirmed data and excludes private cost/profit fields.
 await page.locator('.party-balance-row').filter({hasText:'Unique Alpha'}).click();await page.getByRole('button',{name:'Print Statement',exact:true}).click();await page.evaluate(()=>{window.print=()=>{window.printedText=document.querySelector('.account-print-output').innerText;window.dispatchEvent(new Event('afterprint'));};});await page.getByRole('button',{name:'Detailed Ledger Statement Includes each invoice’s items'}).click();await page.getByRole('button',{name:'Print Detailed Ledger Statement',exact:true}).click();await page.waitForFunction(()=>window.printedText);assert.match(await page.evaluate(()=>window.printedText),/SOFA/);assert.doesNotMatch(await page.evaluate(()=>window.printedText),/Gross profit|Internal unit cost|1,400/i);await closePopup();await page.locator('.invoice-open-row').filter({hasText:'RF-S-000001'}).click();await page.evaluate(()=>{window.printedText='';});await page.locator('dialog[open] .record-menu>summary').click();await page.getByRole('button',{name:'Print Invoice',exact:true}).click();await page.waitForFunction(()=>window.printedText);assert.match(await page.evaluate(()=>window.printedText),/RF-S-000001/);assert.match(await page.evaluate(()=>window.printedText),/DC-100/);assert.doesNotMatch(await page.evaluate(()=>window.printedText),/Gross profit|Internal unit cost|1,400/i);await closePopup();await page.locator('.sidebar').getByRole('button',{name:/Dashboard/}).click();
 // Older supported deployments still confirm writes with a fresh read.
 legacyReplies=true;const readsBeforeLegacy=calls.filter(action=>action==='listAccounts').length;await openNew();await form().getByRole('combobox',{name:/Party/}).fill('Uni');await form().getByRole('combobox',{name:/Party/}).press('Enter');await form().getByLabel('Item 1 description').fill('Legacy response');await form().getByLabel('Rate (₹)',{exact:true}).fill('13');await form().getByRole('button',{name:/Issue invoice/}).click();await page.locator('dialog[open] .invoice-document').waitFor();await page.waitForFunction(()=>!localStorage.getItem('rf.accounts.pending'));assert.ok(calls.filter(action=>action==='listAccounts').length>readsBeforeLegacy);legacyReplies=false;await closePopup();
 // A slow old refresh must not remove a newly confirmed invoice.
 let releaseRead;readGate=new Promise(resolve=>releaseRead=resolve);const readsBeforeRace=calls.filter(action=>action==='listAccounts').length;await page.locator('.period-bar .refresh').click();await new Promise(resolve=>setTimeout(resolve,100));assert.ok(calls.filter(action=>action==='listAccounts').length>readsBeforeRace);await openNew();await form().getByRole('combobox',{name:/Party/}).fill('Uni');await form().getByRole('combobox',{name:/Party/}).press('Enter');await form().getByLabel('Item 1 description').fill('Refresh race');await form().getByLabel('Rate (₹)',{exact:true}).fill('14');await form().getByRole('button',{name:/Issue invoice/}).click();await page.locator('dialog[open] .invoice-document').waitFor();await page.waitForFunction(()=>!localStorage.getItem('rf.accounts.pending'));const raceNumber=backend.post('listAccounts',{}).invoices.at(-1).invoiceNumber;readGate=null;releaseRead();await new Promise(resolve=>setTimeout(resolve,150));assert.match(await page.locator('.invoice-document').innerText(),new RegExp(raceNumber));await closePopup();
 // Keyboard create row, Escape, mobile and page errors.
 await openNew();await form().getByRole('combobox',{name:/Party/}).fill('Uni');await form().getByRole('combobox',{name:/Party/}).press('ArrowDown');await form().getByRole('combobox',{name:/Party/}).press('Enter');await page.getByRole('heading',{name:'New party',exact:true}).waitFor();await page.getByRole('button',{name:'Back to invoice',exact:true}).click();await dialog().waitFor();
 await page.setViewportSize({width:390,height:844});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
 // Mobile issue/total remain visible at both ends of the scrollable form.
 const mobileBar=page.locator('.invoice-submit-bar');const beforeBar=await mobileBar.boundingBox();assert.ok(beforeBar.y+beforeBar.height<=844&&beforeBar.y>=0);await form().getByLabel('Item 1 description').fill('Mobile draft');await form().getByLabel('Rate (₹)',{exact:true}).fill('23');assert.match(await mobileBar.innerText(),/23/);await page.locator('.invoice-edit-content').evaluate(element=>{element.scrollTop=element.scrollHeight;});const afterBar=await mobileBar.boundingBox();assert.ok(Math.abs(beforeBar.y-afterBar.y)<2);await page.locator('.invoice-edit-content').evaluate(element=>{element.scrollTop=0;});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
 await page.screenshot({path:`${artifacts}/invoice-flow-mobile.png`,fullPage:true});
 await form().getByRole('combobox',{name:/Party/}).fill('Uni');await form().getByRole('combobox',{name:/Party/}).press('Escape');assert.equal(await page.locator('[role=listbox]').count(),0);assert.equal(await page.locator('dialog[open]').count(),1);await form().getByRole('combobox',{name:/Party/}).press('Escape');await page.waitForFunction(()=>!document.querySelector('dialog[open]'));assert.equal(await page.evaluate(()=>document.body.style.overflow),'');assert.deepEqual(errors,[]);
 // Resume and submit using the anchored mobile action; issuing clears the draft.
 await page.locator('.dashboard-actions').getByRole('button',{name:'Resume draft',exact:true}).click();await dialog().waitFor();await form().getByRole('combobox',{name:/Party/}).fill('Uni');await form().getByRole('combobox',{name:/Party/}).press('Enter');await page.setViewportSize({width:320,height:700});const narrowBar=await mobileBar.boundingBox();assert.ok(narrowBar.x>=0&&narrowBar.x+narrowBar.width<=320);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);await mobileBar.getByRole('button',{name:/Issue invoice/}).click();await page.locator('dialog[open] .invoice-document').waitFor();await page.waitForFunction(()=>!localStorage.getItem('rf.accounts.pending'));assert.match(await page.locator('.invoice-document').innerText(),/MOBILE DRAFT/);await closePopup();assert.equal(await page.locator('.dashboard-actions').getByRole('button',{name:'Resume draft',exact:true}).isDisabled(),true);
 await page.evaluate(()=>{const key='rf.invoiceDraft.https://script.google.com/macros/s/TEST-ONLY/exec';localStorage.setItem(key,'{broken');});await page.reload();await page.locator('.dashboard-actions').getByRole('button',{name:/New Invoice \/ Note/}).waitFor();assert.equal(await page.evaluate(()=>localStorage.getItem('rf.invoiceDraft.https://script.google.com/macros/s/TEST-ONLY/exec.recovery')),'{broken');assert.deepEqual(errors,[]);
 console.log(JSON.stringify({passed:true,partyReturnMs:partyLatency,invoicePreviewMs:invoiceLatency,actions:calls,errors}));
}catch(error){await page.screenshot({path:`${artifacts}/invoice-flow-failure.png`,fullPage:true});console.error(await page.locator('body').innerText());throw error;}finally{await browser.close();}
