import assert from 'node:assert/strict';
import {mkdir} from 'node:fs/promises';
import {accountBackend} from '../helpers/accountBackend.js';
import {makeParty,makeInvoice} from '../../src/accounts.js';
import {localNow} from '../../src/ledger.js';
const {chromium}=await import(process.env.PLAYWRIGHT_MODULE||'playwright');
const backend=accountBackend(),date=localNow().slice(0,10),errors=[];
const party=makeParty({name:'Stock customer',phone:'',address:'',openingDate:'2026-01-01',openingBalance:'0'},'stock-browser-party-000001');backend.post('createParty',party);
const invoice=makeInvoice({partyId:party.id,type:'sale',invoiceDate:date,notes:'',items:[{description:'SCREW',quantity:'2',rate:'100',cost:'50',discount:'0'},{description:'ORDER ITEM',quantity:'1',rate:'100',cost:'50',discount:'0'},...Array.from({length:24},(_,i)=>({description:`REFERENCE ITEM ${i+1}`,quantity:'1',rate:'100',cost:'50',discount:'0'}))]},'stock-browser-invoice-0001');backend.post('createInvoice',invoice);
const browser=await chromium.launch({headless:true,args:['--no-sandbox']});const context=await browser.newContext({viewport:{width:1440,height:1000},serviceWorkers:'block'});
await context.addInitScript(()=>{const endpoint='https://script.google.com/macros/s/TEST-ONLY/exec';localStorage.setItem('rf.endpoint',JSON.stringify(endpoint));localStorage.setItem('rf.connectionInfo',JSON.stringify({endpoint,version:'1.24.0'}));});
let loseReply=false,holdEdit=null,loseEditReplies=0;
await context.route('https://script.google.com/**',async route=>{const {action,transaction}=route.request().postDataJSON();if(action==='updateStockItem'&&holdEdit)await holdEdit;const result=backend.post(action,transaction);if(loseEditReplies>0&&action==='updateStockItem'){loseEditReplies--;await route.abort('failed');return;}if(loseReply&&action==='recordStock'){loseReply=false;await route.abort('failed');return;}await route.fulfill({json:result});});
const page=await context.newPage();page.setDefaultTimeout(10000);page.on('pageerror',e=>errors.push(e.message));page.on('dialog',dialog=>dialog.accept(dialog.type()==='prompt'?'Wrong stock update':undefined));
const popup=()=>page.locator('dialog[open]');const read=()=>backend.post('listStock',{});await mkdir('/tmp/ledger-browser-results',{recursive:true});
try{
 await page.goto(process.env.LEDGER_TEST_URL||'http://127.0.0.1:5175');await page.keyboard.press('Alt+Shift+5');await page.getByRole('heading',{name:'Stock',exact:true}).waitFor();await page.getByRole('button',{name:'Import opening stock',exact:true}).click();await popup().getByRole('button',{name:'Configure units first',exact:true}).click();
 const csv='Instructions\nItem ID,"Item Name*\n(mandatory field)",Item code,Current stock,Sales Price,Purchase Price,Low stock alert quantity\nsource-screw,SCREW,MODEL-1,6.988,1,800,1\nsource-aluminium,ALUMINIUM,BROWN,25,400,300,5\nsource-generic,GENERIC SALE,,-612.03,0,0,\ndba29746-fdbe-4dca-91c7-89898ab7f8d5,PVC DOMAL U CHANNEL WHITE,WHITE,10.15384615,130,121,\nsource-door,YASH PVC DOOR,MODEL-D,2,1400,1050,\nsource-sheet,ACP SHEET BLACK,MODEL-S,3,3000,2640,\n';
 await popup().locator('input[type=file]').setInputFiles({name:'stock.csv',mimeType:'text/csv',buffer:Buffer.from(csv)});
 await popup().getByText('6 entries · 5 included · 3 needing review',{exact:true}).waitFor();assert.match(await popup().innerText(),/6 entries · 5 included · 3 needing review/);assert.equal(await popup().getByRole('button',{name:'Import opening stock',exact:true}).isDisabled(),true);
 assert.equal(await popup().getByLabel('Base unit YASH PVC DOOR MODEL-D',{exact:true}).count(),0);await popup().getByLabel('Import review filter',{exact:true}).selectOption('all');assert.equal(await popup().getByLabel('Base unit YASH PVC DOOR MODEL-D',{exact:true}).inputValue(),'NOS');assert.equal(await popup().getByLabel('Base unit ACP SHEET BLACK MODEL-S',{exact:true}).inputValue(),'SHEET');assert.equal(await popup().getByLabel('Purchase price unit ACP SHEET BLACK MODEL-S',{exact:true}).inputValue(),'SHEET');await popup().getByLabel('Import review filter',{exact:true}).selectOption('pending');
 const domal=popup().locator('.stock-import-row').filter({hasText:'PVC DOMAL U CHANNEL WHITE'});assert.match(await domal.innerText(),/253.84615375 PCS is fractional/);assert.equal(await popup().getByLabel('Conversion PVC DOMAL U CHANNEL WHITE WHITE',{exact:true}).inputValue(),'25');await domal.getByRole('checkbox',{name:'Include in stock',exact:true}).uncheck();
 await popup().getByLabel('Base unit SCREW MODEL-1',{exact:true}).selectOption('PCS');await popup().getByLabel('Secondary unit SCREW MODEL-1',{exact:true}).selectOption('BOX');await popup().getByLabel('Conversion SCREW MODEL-1',{exact:true}).fill('1000');await popup().getByLabel('CSV quantity unit SCREW MODEL-1',{exact:true}).selectOption('BOX');await popup().getByLabel('Sale price unit SCREW MODEL-1',{exact:true}).selectOption('PCS');await popup().getByLabel('Purchase price unit SCREW MODEL-1',{exact:true}).selectOption('BOX');
 await popup().getByLabel('Base unit ALUMINIUM BROWN',{exact:true}).selectOption('KG');await popup().getByLabel('Secondary unit ALUMINIUM BROWN',{exact:true}).selectOption('GRAM');await popup().getByLabel('Conversion ALUMINIUM BROWN',{exact:true}).fill('0.001');await popup().getByLabel('Sale price unit ALUMINIUM BROWN',{exact:true}).selectOption('KG');await popup().getByLabel('Purchase price unit ALUMINIUM BROWN',{exact:true}).selectOption('KG');
 await popup().getByRole('button',{name:'Close popup'}).click();await page.getByRole('button',{name:'Import opening stock',exact:true}).click();await popup().getByRole('button',{name:'Configure units first',exact:true}).click();await popup().getByLabel('Import review filter',{exact:true}).selectOption('all');assert.equal(await popup().getByLabel('Conversion SCREW MODEL-1',{exact:true}).inputValue(),'1000');await popup().getByRole('button',{name:'Import opening stock',exact:true}).click();await popup().waitFor({state:'detached'});assert.equal(read().items.length,4);assert.equal(read().items[0].balance,'6988');
 const stockTable=page.locator('.stock-table');assert.equal(await stockTable.locator('tbody tr').count(),4);const screwRow=stockTable.locator('tbody tr').filter({hasText:'MODEL-1'});assert.match(await screwRow.innerText(),/6988/);assert.match(await screwRow.innerText(),/5,590.40/);assert.match(await screwRow.innerText(),/BOX/);await page.screenshot({path:'/tmp/ledger-browser-results/stock-table-desktop.png',fullPage:true});
 await page.getByRole('button',{name:'Update Stock',exact:true}).click();await popup().getByRole('combobox',{name:'Search stock item'}).waitFor();
 assert.equal(await popup().getByLabel('Pending invoice',{exact:true}).inputValue(),invoice.id);assert.equal(await popup().locator('[role=option]').count(),0);assert.match(await popup().locator('.stock-pos-invoice').innerText(),/ORDER ITEM/);
 const search=popup().getByRole('combobox',{name:'Search stock item'});await search.fill('SCREW');await search.press('Enter');const quantity=popup().getByLabel('Quantity SCREW · MODEL-1',{exact:true});await quantity.fill('2');await popup().getByLabel('Unit SCREW · MODEL-1',{exact:true}).selectOption('BOX');await quantity.press('Enter');assert.equal(await search.evaluate(el=>el===document.activeElement),true);
 await page.keyboard.press('Control+k');assert.equal(await search.evaluate(el=>el===document.activeElement),true);
 await page.keyboard.press('Alt+m');assert.match(await popup().locator('.stock-pos-metrics').innerText(),/6988.*PCS/s);await page.keyboard.press('Alt+m');
 await page.keyboard.press('Alt+h');assert.match(await popup().locator('.stock-pos-keys').innerText(),/Alt Backspace/);await page.keyboard.press('Alt+h');
 await page.keyboard.press('Alt+d');assert.equal(await popup().getByLabel('Movement date',{exact:true}).evaluate(el=>el===document.activeElement),true);await page.keyboard.press('Alt+o');
 await search.fill('ALUMINIUM');await search.press('Enter');const extraQuantity=popup().getByLabel('Quantity ALUMINIUM · BROWN',{exact:true});await extraQuantity.fill('1');await page.keyboard.press('Alt+u');assert.equal(await popup().getByLabel('Unit ALUMINIUM · BROWN',{exact:true}).evaluate(el=>el===document.activeElement),true);
 await page.keyboard.press('Alt+q');assert.equal(await extraQuantity.evaluate(el=>el===document.activeElement),true);await page.keyboard.press('Alt+ArrowUp');assert.equal(await quantity.evaluate(el=>el===document.activeElement),true);await page.keyboard.press('Alt+ArrowDown');assert.equal(await extraQuantity.evaluate(el=>el===document.activeElement),true);await page.keyboard.press('Alt+Backspace');assert.equal(await extraQuantity.count(),0);
 const separator=popup().getByRole('separator',{name:'Resize invoice and stock panels'});await separator.focus();await separator.press('ArrowRight');assert.equal(await separator.getAttribute('aria-valuenow'),'55');
 const handle=await separator.boundingBox();await page.mouse.move(handle.x+handle.width/2,handle.y+handle.height/2);await page.mouse.down();await page.mouse.move(handle.x-100,handle.y+handle.height/2);await page.mouse.up();assert.ok(Number(await separator.getAttribute('aria-valuenow'))<55);
 await popup().getByText('Options',{exact:true}).click();assert.equal(await popup().getByLabel('Movement date',{exact:true}).isVisible(),true);await popup().getByText('Options',{exact:true}).click();
 await page.setViewportSize({width:1440,height:650});
 for(let i=0;i<10;i++){await search.fill('SCREW');await search.press('Enter');}
 const fixedSearch=await search.boundingBox(),saveButton=popup().getByRole('button',{name:'Save stock & Next',exact:true}),fixedSave=await saveButton.boundingBox();
 for(const selector of ['.stock-pos-invoice .stock-pos-table-scroll','.stock-pos-editor .stock-pos-table-scroll']){const scroll=popup().locator(selector);assert.equal(await scroll.evaluate(el=>el.scrollHeight>el.clientHeight),true);await scroll.evaluate(el=>{el.scrollTop=el.scrollHeight;});}
 assert.equal(Math.round((await search.boundingBox()).y),Math.round(fixedSearch.y));assert.equal(Math.round((await saveButton.boundingBox()).y),Math.round(fixedSave.y));
 assert.equal(await popup().locator('.stock-pos-split').evaluate(el=>[...el.querySelectorAll(':scope > section')].every(section=>section.scrollHeight===section.clientHeight)),true);
 for(let i=0;i<10;i++)await popup().getByRole('button',{name:'Remove SCREW · MODEL-1',exact:true}).last().click();
 await page.screenshot({path:'/tmp/ledger-browser-results/stock-pos-compact.png',fullPage:true});await page.setViewportSize({width:1440,height:1000});
 await page.screenshot({path:'/tmp/ledger-browser-results/stock-pos-desktop.png',fullPage:true});await page.keyboard.press('Control+Enter');await popup().getByText('No more pending invoices',{exact:true}).waitFor();await page.waitForFunction(()=>!localStorage.getItem('rf.stock-pending:https://script.google.com/macros/s/TEST-ONLY/exec'));assert.equal(read().items[0].balance,'4988');assert.equal(read().reviews.length,invoice.items.length);assert.ok(read().movements.filter(row=>row.invoiceId===invoice.id).every(row=>!row.invoiceItemId));
 await popup().getByRole('button',{name:'Close popup'}).click();await page.getByRole('button',{name:'Stock Update',exact:true}).click();await popup().getByRole('combobox',{name:'Search stock item'}).fill('ALUMINIUM');await popup().getByRole('combobox',{name:'Search stock item'}).press('Enter');await popup().getByLabel('Quantity ALUMINIUM · BROWN',{exact:true}).fill('2750');await popup().getByLabel('Unit ALUMINIUM · BROWN',{exact:true}).selectOption('GRAM');await popup().getByLabel('Reason',{exact:true}).fill('Material used');const manualSearch=popup().getByRole('combobox',{name:'Search stock item'});await manualSearch.fill('SCREW');await manualSearch.press('Enter');await popup().getByLabel('Quantity SCREW · MODEL-1',{exact:true}).fill('1');await popup().getByLabel('Action SCREW · MODEL-1',{exact:true}).selectOption('add');await manualSearch.fill('SCREW');await manualSearch.press('Enter');await popup().getByLabel('Quantity SCREW · MODEL-1',{exact:true}).last().fill('1');loseReply=true;await popup().getByRole('button',{name:'Save stock update',exact:true}).click();await popup().getByLabel('Quantity ALUMINIUM · BROWN',{exact:true}).waitFor({state:'detached'});await page.waitForFunction(()=>!localStorage.getItem('rf.stock-pending:https://script.google.com/macros/s/TEST-ONLY/exec'));assert.equal(read().items[1].balance,'22.25');assert.equal(read().operations.filter(op=>op.kind==='manual').length,1);await popup().getByRole('button',{name:'Close popup'}).click();
 await page.getByRole('button',{name:'Movement history',exact:true}).click();await popup().getByRole('button',{name:'Reverse update',exact:true}).first().click();await page.waitForFunction(()=>!localStorage.getItem('rf.stock-pending:https://script.google.com/macros/s/TEST-ONLY/exec'));assert.equal(read().items[1].balance,'25');await popup().getByRole('button',{name:'Close popup'}).click();
 let releaseEdit;holdEdit=new Promise(resolve=>{releaseEdit=resolve;});loseEditReplies=2;
 await page.getByRole('button',{name:'Edit stock item SCREW · MODEL-1',exact:true}).click();assert.equal(await popup().getByLabel('Base stock unit',{exact:true}).isDisabled(),true);await popup().getByLabel('Secondary stock unit',{exact:true}).selectOption('PACKET');await popup().getByLabel('Secondary unit conversion',{exact:true}).fill('100');await popup().getByLabel('Purchase price unit',{exact:true}).selectOption('PACKET');await popup().getByRole('button',{name:'Save item settings',exact:true}).click();await popup().waitFor({state:'detached'});assert.equal(read().items[0].secondaryUnit,'BOX');await page.locator('.sync-status summary').filter({hasText:'Saving 1 change'}).waitFor();await page.locator('.stock-table').getByText('Saving…',{exact:true}).waitFor();
 // Queue a second item and a further edit of the first while its upload is held.
 await page.getByRole('button',{name:'Edit stock item YASH PVC DOOR · MODEL-D',exact:true}).click();await popup().getByLabel('Sale price (₹)',{exact:true}).fill('1450');await popup().getByRole('button',{name:'Save item settings',exact:true}).click();await popup().waitFor({state:'detached'});
 await page.getByRole('button',{name:'Edit stock item SCREW · MODEL-1',exact:true}).click();assert.equal(await popup().getByLabel('Secondary stock unit',{exact:true}).inputValue(),'PACKET');await popup().getByLabel('Sale price (₹)',{exact:true}).fill('2');await popup().getByRole('button',{name:'Save item settings',exact:true}).click();await popup().waitFor({state:'detached'});
 const queuedEdits=await page.evaluate(()=>JSON.parse(localStorage.getItem('rf.stock-pending:https://script.google.com/macros/s/TEST-ONLY/exec')).queue);assert.equal(queuedEdits.length,3);assert.equal(queuedEdits[2].payload._expectedRevision,1);assert.equal(read().items[0].secondaryUnit,'BOX');assert.equal(await page.locator('.stock-table').getByText('Saving…',{exact:true}).count(),2);
 await page.keyboard.press('Alt+Shift+1');await page.getByRole('heading',{name:'Dashboard',exact:true}).waitFor();releaseEdit();holdEdit=null;await page.keyboard.press('Alt+Shift+5');await page.getByRole('heading',{name:'Stock',exact:true}).waitFor();await page.waitForFunction(()=>JSON.parse(localStorage.getItem('rf.stock-pending:https://script.google.com/macros/s/TEST-ONLY/exec')||'null')?.queue?.[0]?.failed);await page.getByRole('button',{name:'Retry stock update',exact:true}).click();await page.waitForFunction(()=>!localStorage.getItem('rf.stock-pending:https://script.google.com/macros/s/TEST-ONLY/exec'));assert.equal(read().operations.filter(op=>op.kind==='item-edit').length,3);assert.equal(read().items[0].saleRateMinor,200);assert.equal(read().items[0].revision,2);assert.equal(read().items.find(item=>item.code==='MODEL-D').saleRateMinor,145000);assert.equal(read().items[0].balance,'4988');assert.equal(read().items[0].secondaryUnit,'PACKET');assert.equal(read().movements.find(m=>m.stockItemId===read().items[0].id).conversion,'1000');
 await page.getByRole('button',{name:'Edit stock item YASH PVC DOOR · MODEL-D',exact:true}).click();await popup().getByLabel('Secondary stock unit',{exact:true}).selectOption('BOX');await popup().getByLabel('Secondary unit conversion',{exact:true}).fill('10');await popup().getByRole('button',{name:'Save item settings',exact:true}).click();await popup().waitFor({state:'detached'});await page.waitForFunction(()=>!localStorage.getItem('rf.stock-pending:https://script.google.com/macros/s/TEST-ONLY/exec'));const door=read().items.find(item=>item.code==='MODEL-D');assert.equal(door.secondaryUnit,'BOX');assert.equal(door.balance,'2');
 await page.setViewportSize({width:390,height:844});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);await page.getByRole('button',{name:'Update Stock',exact:true}).click();await page.locator('.stock-mobile-tabs').getByRole('button',{name:'Stock entries (0)',exact:true}).click();assert.equal(await page.locator('.stock-update-side').isVisible(),true);assert.equal(await page.locator('.stock-invoice-side').isVisible(),false);await page.setViewportSize({width:320,height:700});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);await page.screenshot({path:'/tmp/ledger-browser-results/stock-mobile.png',fullPage:true});
 await popup().getByRole('button',{name:'Close popup'}).click();await page.setViewportSize({width:1440,height:1000});await page.keyboard.press('Alt+Shift+3');await page.getByRole('heading',{name:'History',exact:true}).waitFor();assert.deepEqual(errors,[]);
 const fastBackend=accountBackend(),fastContext=await browser.newContext({viewport:{width:390,height:844},serviceWorkers:'block'});
 // Private mock fixtures keep purchase/next-invoice coverage independent of production UI.
 const supplier=makeParty({name:'Stock supplier',partyType:'supplier',phone:'',address:'',openingDate:'2026-01-01',openingBalance:'0'},'stock-browser-supplier-001');assert.equal(fastBackend.post('createParty',supplier).ok,true);
 const fixtureInvoices=['purchase','sale'].map((type,index)=>makeInvoice({partyId:supplier.id,type,notes:'',invoiceDate:date,items:[{description:'HARDWARE',quantity:'1',rate:'20',cost:'10',billingUnit:'nos'}]},`stock-browser-fixture-${index+1}`));
 for(const record of fixtureInvoices)assert.equal(fastBackend.post('createInvoice',record).ok,true);
 await fastContext.addInitScript(()=>{const endpoint='https://script.google.com/macros/s/TEST-ONLY/exec';localStorage.setItem('rf.endpoint',JSON.stringify(endpoint));localStorage.setItem('rf.connectionInfo',JSON.stringify({endpoint,version:'1.24.0'}));});
 let lostImport=false;
 await fastContext.route('https://script.google.com/**',async route=>{const {action,transaction}=route.request().postDataJSON();if(action==='reviewInvoiceStock')await new Promise(resolve=>setTimeout(resolve,1500));const result=fastBackend.post(action,transaction);if(action==='importStock'&&!lostImport){lostImport=true;await route.abort('failed');return;}await route.fulfill({json:result});});
 const fastPage=await fastContext.newPage();fastPage.setDefaultTimeout(10000);fastPage.on('pageerror',e=>errors.push(e.message));fastPage.on('dialog',dialog=>dialog.accept());
 await fastPage.goto(process.env.LEDGER_TEST_URL||'http://127.0.0.1:5175');await fastPage.locator('.mobile-nav').getByRole('button',{name:/Stock/}).click();await fastPage.getByRole('button',{name:'Import opening stock',exact:true}).click();
 const fastPopup=()=>fastPage.locator('dialog[open]');assert.equal(await fastPopup().getByRole('button',{name:'Import as exported',exact:true}).getAttribute('aria-pressed'),'true');
 const fastCsv='Item ID,Item Name*,Current stock,Sales Price,Purchase Price,Low stock alert quantity\nunknown-direct,HARDWARE,7.25,20.50,10.25,1\nb6b6ba7f-cf52-4b3d-b7aa-3bdb03312de6,SCREW 13 x 6 SELF,6.988,350,260,1\ndba29746-fdbe-4dca-91c7-89898ab7f8d5,PVC DOMAL U CHANNEL WHITE,10.15384615,130,121,1\ngeneric-direct,GENERIC SALE,-612.03,0,0,\n';
 await fastPopup().locator('input[type=file]').setInputFiles({name:'direct.csv',mimeType:'text/csv',buffer:Buffer.from(fastCsv)});await fastPopup().getByText(/4 entries · 3 included/).waitFor();assert.equal(await fastPopup().getByRole('button',{name:'Import opening stock',exact:true}).isEnabled(),true);assert.equal(await fastPopup().getByLabel(/Base unit/).count(),0);assert.match(await fastPopup().innerText(),/7.25 CSV unit/);assert.match(await fastPopup().innerText(),/6.988 BOX/);await fastPage.setViewportSize({width:320,height:700});assert.equal(await fastPage.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);assert.ok((await fastPopup().locator('.stock-export-preview').boundingBox()).height>=100);await fastPage.screenshot({path:'/tmp/ledger-browser-results/stock-direct-import.png',fullPage:true});
 await fastPopup().getByRole('button',{name:'Import opening stock',exact:true}).click();await fastPopup().waitFor({state:'detached'});const direct=fastBackend.post('listStock',{});assert.equal(direct.items.length,3);assert.equal(direct.operations.filter(op=>op.kind==='opening').length,1);assert.equal(direct.items.find(item=>item.sourceId==='unknown-direct').balance,'7.25');assert.equal(direct.items.find(item=>item.sourceId==='b6b6ba7f-cf52-4b3d-b7aa-3bdb03312de6').balance,'6988');assert.equal(direct.items.find(item=>item.sourceId==='dba29746-fdbe-4dca-91c7-89898ab7f8d5').balance,'253.84615375');assert.equal(fastBackend.post('listAccounts',{}).transactions.length,0);
 await fastPage.getByRole('button',{name:'Edit stock item HARDWARE',exact:true}).click();assert.equal(await fastPopup().getByLabel('Base stock unit',{exact:true}).isEnabled(),true);await fastPopup().getByLabel('Base stock unit',{exact:true}).selectOption('KG');await fastPopup().getByLabel('Secondary stock unit',{exact:true}).selectOption('GRAM');await fastPopup().getByLabel('Secondary unit conversion',{exact:true}).fill('0.001');await fastPopup().getByRole('button',{name:'Save item settings',exact:true}).click();await fastPopup().waitFor({state:'detached'});await fastPage.waitForFunction(()=>!localStorage.getItem('rf.stock-pending:https://script.google.com/macros/s/TEST-ONLY/exec'));const assigned=fastBackend.post('listStock',{}).items.find(item=>item.sourceId==='unknown-direct');assert.equal(assigned.balance,'7.25');assert.equal(assigned.baseUnit,'KG');assert.equal(assigned.secondaryUnit,'GRAM');assert.equal(await fastPage.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);await fastPage.locator('.stock-item-link').filter({hasText:'HARDWARE'}).click();await fastPopup().getByRole('heading',{name:'HARDWARE',exact:true}).waitFor();assert.match(await fastPopup().locator('.stock-history-table').innerText(),/Opening stock import/);await fastPopup().getByRole('button',{name:'Close popup'}).click();
 await fastPage.getByRole('button',{name:'Update Stock',exact:true}).click();await fastPopup().getByLabel('Pending invoice',{exact:true}).selectOption(fixtureInvoices.find(row=>row.type==='purchase').id);await fastPopup().locator('.stock-pos-invoice-heading').getByText(/PURCHASE/).waitFor();const purchaseId=fixtureInvoices.find(row=>row.type==='purchase').id;const fastSearch=fastPopup().getByRole('combobox',{name:'Search stock item'});await fastPage.locator('.stock-mobile-tabs').getByRole('button',{name:'Stock entries (0)',exact:true}).click();await fastSearch.fill('HARDWARE');await fastSearch.press('Enter');await fastPopup().getByLabel('Quantity HARDWARE',{exact:true}).fill('1');await fastPopup().getByLabel('Purchase price HARDWARE',{exact:true}).fill('12');await fastPopup().getByRole('button',{name:'Save stock & Next',exact:true}).click();await fastPopup().getByLabel('Pending invoice',{exact:true}).waitFor({state:'attached'});await fastPage.waitForFunction(()=>document.querySelector('#stock-pos-search')===document.activeElement);assert.equal(await fastSearch.isEnabled(),true);assert.equal(await fastPopup().getByRole('button',{name:'Close popup'}).isEnabled(),true);assert.ok(await fastPage.evaluate(()=>!!localStorage.getItem('rf.stock-pending:https://script.google.com/macros/s/TEST-ONLY/exec')));await fastPage.waitForFunction(()=>!localStorage.getItem('rf.stock-pending:https://script.google.com/macros/s/TEST-ONLY/exec'));assert.equal(fastBackend.post('listStock',{}).items.find(item=>item.name==='HARDWARE').balance,'8.25');assert.equal(fastBackend.post('listStock',{}).items.find(item=>item.name==='HARDWARE').purchaseRateMinor,1200);
 await fastPage.keyboard.press('Alt+1');await fastPage.keyboard.press('Alt+p');await fastPage.waitForFunction(id=>document.querySelector('[aria-label="Pending invoice"]')?.value===id,purchaseId);await fastPage.keyboard.press('Alt+p');await fastPage.waitForFunction(id=>document.querySelector('[aria-label="Pending invoice"]')?.value!==id,purchaseId);await fastPage.keyboard.press('Alt+p');await fastPage.waitForFunction(id=>document.querySelector('[aria-label="Pending invoice"]')?.value===id,purchaseId);await fastPage.keyboard.press('Alt+2');await fastPopup().getByRole('button',{name:'Correct saved stock',exact:true}).click();await fastPopup().getByLabel('Quantity HARDWARE',{exact:true}).waitFor({state:'visible'});await fastPage.waitForFunction(()=>!localStorage.getItem('rf.stock-pending:https://script.google.com/macros/s/TEST-ONLY/exec'));await fastPopup().getByLabel('Quantity HARDWARE',{exact:true}).fill('2');await fastPopup().getByRole('button',{name:'Save adjustment & Next',exact:true}).click();await fastPage.waitForFunction(()=>!localStorage.getItem('rf.stock-pending:https://script.google.com/macros/s/TEST-ONLY/exec'));assert.equal(fastBackend.post('listStock',{}).items.find(item=>item.name==='HARDWARE').balance,'9.25');
 await fastSearch.fill('HARDWARE');await fastSearch.press('Enter');await fastPopup().getByLabel('Quantity HARDWARE',{exact:true}).fill('100');await fastPopup().getByText(/Negative stock: HARDWARE/).waitFor();assert.equal(await fastPopup().getByRole('button',{name:'Save stock & Next',exact:true}).isDisabled(),true);await fastPage.keyboard.press('Alt+n');assert.equal(await fastPopup().getByRole('button',{name:'Save stock & Next',exact:true}).isEnabled(),true);await fastPopup().getByRole('button',{name:'Remove HARDWARE',exact:true}).click();await fastPopup().getByRole('button',{name:'Close popup'}).click();
 await fastPage.getByLabel('Select all visible stock',{exact:true}).check();await fastPage.getByRole('button',{name:'Bulk edit',exact:true}).click();await fastPopup().getByLabel('Selling price (₹)',{exact:true}).fill('25');await fastPopup().getByRole('button',{name:'Apply changes',exact:true}).click();await fastPopup().waitFor({state:'detached'});assert.ok(fastBackend.post('listStock',{}).items.every(item=>item.saleRateMinor===2500));
 await fastPage.locator('.stock-metric-buttons').getByRole('button',{name:/Fast moving/}).click();assert.equal(await fastPage.locator('.stock-table tbody tr').count(),0);await fastPage.locator('.stock-metric-buttons').getByRole('button',{name:/Slow moving/}).click();assert.equal(await fastPage.locator('.stock-table tbody tr').count(),3);await fastPage.locator('.stock-metric-buttons').getByRole('button',{name:/Total stock value/}).click();
 await fastPage.getByRole('button',{name:'Delete stock item HARDWARE',exact:true}).click();await fastPage.getByRole('button',{name:'Delete stock item HARDWARE',exact:true}).waitFor({state:'detached'});assert.equal(fastBackend.post('listStock',{}).items.filter(item=>item.status==='deleted').length,1);
 await fastPage.getByLabel('Select all visible stock',{exact:true}).check();await fastPage.getByRole('button',{name:'Delete selected',exact:true}).click();await fastPage.getByRole('button',{name:'Delete selected',exact:true}).waitFor({state:'detached'});assert.equal(await fastPage.locator('.stock-table tbody tr').count(),0);assert.equal(fastBackend.post('listStock',{}).items.filter(item=>item.status==='deleted').length,3);assert.equal(fastBackend.post('listStock',{}).movements.length,5);
 assert.deepEqual(errors,[]);await fastContext.close();
 // Background uploads must drain even while the Stock page is unmounted.
 const backgroundBackend=accountBackend(),backgroundContext=await browser.newContext({serviceWorkers:'block'});
 const backgroundItem={id:'stock-background-item001',name:'BACKGROUND KG',baseUnit:'KG',secondaryUnit:'',conversion:'1',saleRateMinor:10000,purchaseRateMinor:5000,saleRateUnit:'KG',purchaseRateUnit:'KG',lowStock:'1',quantity:'10',importUnit:'KG'};
 assert.equal(backgroundBackend.post('importStock',{id:'stock-background-open001',openingDate:'2026-01-01',items:[backgroundItem]}).ok,true);
 await backgroundContext.addInitScript(({item,date})=>{const endpoint='https://script.google.com/macros/s/TEST-ONLY/exec';localStorage.setItem('rf.endpoint',JSON.stringify(endpoint));localStorage.setItem('rf.connectionInfo',JSON.stringify({endpoint,version:'1.24.0'}));localStorage.setItem('rf.stock-pending:'+endpoint,JSON.stringify({queue:[1,2].map(n=>({action:'recordStock',payload:{id:'stock-background-save00'+n,stockMovementSchemaVersion:1,movementDate:date,reason:'Background regression',movements:[{stockItemId:item.id,expectedRevision:0,quantity:'-1',unit:'KG'}]}}))}));},{item:backgroundItem,date});
 let releaseFirst,backgroundSends=0;const firstHeld=new Promise(resolve=>{releaseFirst=resolve;});
 await backgroundContext.route('https://script.google.com/**',async route=>{const {action,transaction}=route.request().postDataJSON();if(action==='recordStock'){backgroundSends++;if(backgroundSends===1)await firstHeld;}await route.fulfill({json:backgroundBackend.post(action,transaction)});});
 const backgroundPage=await backgroundContext.newPage();backgroundPage.on('pageerror',error=>errors.push(error.message));
 try{
  await backgroundPage.goto(process.env.LEDGER_TEST_URL||'http://127.0.0.1:5175');await backgroundPage.locator('.sidebar').getByRole('button',{name:/Stock/}).click();await backgroundPage.getByRole('heading',{name:'Stock',exact:true}).waitFor();
  await backgroundPage.locator('.sync-status summary').filter({hasText:'Saving 2 changes'}).waitFor();
  await backgroundPage.keyboard.press('Alt+Shift+1');await backgroundPage.getByRole('heading',{name:'Dashboard',exact:true}).waitFor();releaseFirst();
  await backgroundPage.waitForFunction(()=>!localStorage.getItem('rf.stock-pending:https://script.google.com/macros/s/TEST-ONLY/exec'));assert.equal(backgroundSends,2);assert.equal(backgroundBackend.post('listStock',{}).items[0].balance,'8');
 }finally{releaseFirst();await backgroundContext.close();}
 assert.deepEqual(errors,[]);
 console.log(JSON.stringify({passed:true,scenarios:'one-click as-exported import, exact source fractions, unknown units assigned later, lost import acknowledgement, mobile preview, automatic door/sheet/price rules, editing and adding secondary units, historical conversion preservation, unit review, import draft recovery, model IDs, boxes, KG, no-impact, finish-next, background retry, reversals, mobile tabs, history navigation, mobile item history, bulk edits, single and bulk deletion, metric filters, background queue navigation, multiple background item edits, repeated-item revision chaining and lost-acknowledgement retry',errors}));
}catch(e){await page.screenshot({path:'/tmp/ledger-browser-results/stock-failure.png',fullPage:true});console.error((await page.locator('body').innerText()).slice(-6500));throw e;}finally{await browser.close();}
