import assert from 'node:assert/strict';
import {mkdir} from 'node:fs/promises';
import {accountBackend} from '../helpers/accountBackend.js';
import {makeParty,makeInvoice} from '../../src/accounts.js';
import {localNow} from '../../src/ledger.js';
const {chromium}=await import(process.env.PLAYWRIGHT_MODULE||'playwright');
const backend=accountBackend(),date=localNow().slice(0,10),errors=[];
const party=makeParty({name:'Stock customer',phone:'',address:'',openingDate:'2026-01-01',openingBalance:'0'},'stock-browser-party-000001');backend.post('createParty',party);
const invoice=makeInvoice({partyId:party.id,type:'sale',invoiceDate:date,notes:'',items:[{description:'SCREW',quantity:'2',rate:'100',cost:'50',discount:'0'},{description:'ORDER ITEM',quantity:'1',rate:'100',cost:'50',discount:'0'}]},'stock-browser-invoice-0001');backend.post('createInvoice',invoice);
const browser=await chromium.launch({headless:true,args:['--no-sandbox']});const context=await browser.newContext({viewport:{width:1440,height:1000},serviceWorkers:'block'});
await context.addInitScript(()=>{const endpoint='https://script.google.com/macros/s/TEST-ONLY/exec';localStorage.setItem('rf.endpoint',JSON.stringify(endpoint));localStorage.setItem('rf.connectionInfo',JSON.stringify({endpoint,version:'1.23.0'}));});
let loseReply=false;
await context.route('https://script.google.com/**',async route=>{const {action,transaction}=route.request().postDataJSON();const result=backend.post(action,transaction);if(loseReply&&action==='recordStock'){loseReply=false;await route.abort('failed');return;}await route.fulfill({json:result});});
const page=await context.newPage();page.setDefaultTimeout(10000);page.on('pageerror',e=>errors.push(e.message));page.on('dialog',dialog=>dialog.accept(dialog.type()==='prompt'?'Wrong stock update':undefined));
const popup=()=>page.locator('dialog[open]');const read=()=>backend.post('listStock',{});await mkdir('/tmp/ledger-browser-results',{recursive:true});
try{
 await page.goto(process.env.LEDGER_TEST_URL||'http://127.0.0.1:5175');await page.keyboard.press('Alt+Shift+5');await page.getByRole('heading',{name:'Stock',exact:true}).waitFor();await page.getByRole('button',{name:'Import opening stock',exact:true}).click();
 const csv='Instructions\nItem ID,"Item Name*\n(mandatory field)",Item code,Current stock,Sales Price,Purchase Price,Low stock alert quantity\nsource-screw,SCREW,MODEL-1,6.988,1,800,1\nsource-aluminium,ALUMINIUM,BROWN,25,400,300,5\nsource-generic,GENERIC SALE,,-612.03,0,0,\n';
 await popup().locator('input[type=file]').setInputFiles({name:'stock.csv',mimeType:'text/csv',buffer:Buffer.from(csv)});
 assert.match(await popup().innerText(),/3 entries · 2 included · 2 awaiting units/);assert.equal(await popup().getByRole('button',{name:'Import opening stock',exact:true}).isDisabled(),true);
 await popup().getByLabel('Base unit SCREW MODEL-1',{exact:true}).selectOption('PCS');await popup().getByLabel('Secondary unit SCREW MODEL-1',{exact:true}).selectOption('BOX');await popup().getByLabel('Conversion SCREW MODEL-1',{exact:true}).fill('1000');await popup().getByLabel('CSV quantity unit SCREW MODEL-1',{exact:true}).selectOption('BOX');await popup().getByLabel('Sale price unit SCREW MODEL-1',{exact:true}).selectOption('PCS');await popup().getByLabel('Purchase price unit SCREW MODEL-1',{exact:true}).selectOption('BOX');
 await popup().getByLabel('Base unit ALUMINIUM BROWN',{exact:true}).selectOption('KG');await popup().getByLabel('Secondary unit ALUMINIUM BROWN',{exact:true}).selectOption('GRAM');await popup().getByLabel('Conversion ALUMINIUM BROWN',{exact:true}).fill('0.001');await popup().getByLabel('Sale price unit ALUMINIUM BROWN',{exact:true}).selectOption('KG');await popup().getByLabel('Purchase price unit ALUMINIUM BROWN',{exact:true}).selectOption('KG');
 await popup().getByRole('button',{name:'Close popup'}).click();await page.getByRole('button',{name:'Import opening stock',exact:true}).click();assert.equal(await popup().getByLabel('Conversion SCREW MODEL-1',{exact:true}).inputValue(),'1000');await popup().getByRole('button',{name:'Import opening stock',exact:true}).click();await popup().waitFor({state:'detached'});assert.equal(read().items.length,2);assert.equal(read().items[0].balance,'6988');
 await page.getByRole('button',{name:'Update Stock',exact:true}).click();await page.locator('.stock-queue-row').first().click();await page.getByLabel('Stock action SCREW',{exact:true}).waitFor();await page.getByLabel('Stock action SCREW',{exact:true}).selectOption('updated');await page.getByLabel('Material SCREW 1',{exact:true}).selectOption(read().items[0].id);await page.getByLabel('Material quantity SCREW 1',{exact:true}).fill('2');await page.getByLabel('Material unit SCREW 1',{exact:true}).selectOption('BOX');await page.getByLabel('Stock action ORDER ITEM',{exact:true}).selectOption('no-impact');await page.getByRole('button',{name:'Finish & Next Invoice',exact:true}).click();await page.waitForFunction(()=>!localStorage.getItem('rf.stock-pending:https://script.google.com/macros/s/TEST-ONLY/exec'));await page.getByText('All eligible invoices have been reviewed.').waitFor();assert.equal(read().items[0].balance,'4988');assert.equal(read().reviews.length,2);
 await page.getByRole('button',{name:'Back to stock',exact:true}).click();await page.getByRole('button',{name:'Manual stock update',exact:true}).click();await popup().getByLabel('Stock item',{exact:true}).selectOption(read().items[1].id);await popup().getByLabel('Quantity',{exact:true}).fill('2750');await popup().getByLabel('Movement unit',{exact:true}).selectOption('GRAM');await popup().getByLabel('Reason',{exact:true}).fill('Material used');loseReply=true;await popup().getByRole('button',{name:'Save stock update',exact:true}).click();await popup().waitFor({state:'detached'});assert.equal(read().items[1].balance,'22.25');assert.equal(read().operations.filter(op=>op.kind==='manual').length,1);
 await page.getByRole('button',{name:'Movement history',exact:true}).click();await popup().getByRole('button',{name:'Reverse update',exact:true}).first().click();await page.waitForFunction(()=>!localStorage.getItem('rf.stock-pending:https://script.google.com/macros/s/TEST-ONLY/exec'));assert.equal(read().items[1].balance,'25');await popup().getByRole('button',{name:'Close popup'}).click();
 await page.setViewportSize({width:390,height:844});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);await page.getByRole('button',{name:'Update Stock',exact:true}).click();await page.locator('.stock-mobile-tabs').getByRole('button',{name:'Stock update',exact:true}).click();assert.equal(await page.locator('.stock-update-side').isVisible(),true);assert.equal(await page.locator('.stock-invoice-side').isVisible(),false);await page.setViewportSize({width:320,height:700});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);await page.screenshot({path:'/tmp/ledger-browser-results/stock-mobile.png',fullPage:true});
 await page.setViewportSize({width:1440,height:1000});await page.keyboard.press('Alt+Shift+3');await page.getByRole('heading',{name:'History',exact:true}).waitFor();assert.deepEqual(errors,[]);console.log(JSON.stringify({passed:true,scenarios:'unit review, import draft recovery, model IDs, boxes, KG, no-impact, finish-next, background retry, reversals, mobile tabs, history navigation',errors}));
}catch(e){await page.screenshot({path:'/tmp/ledger-browser-results/stock-failure.png',fullPage:true});console.error((await page.locator('body').innerText()).slice(-6500));throw e;}finally{await browser.close();}
