import assert from 'node:assert/strict';
import {mkdir} from 'node:fs/promises';
import {accountBackend} from '../helpers/accountBackend.js';
import {localNow} from '../../src/ledger.js';
const {chromium}=await import(process.env.PLAYWRIGHT_MODULE||'playwright');
const endpoint='https://script.google.com/macros/s/TEST-ONLY/exec',backend=accountBackend(),errors=[],date=localNow().slice(0,10);
const item={id:'sync-stock-item-00000001',name:'SCREW',baseUnit:'PCS',secondaryUnit:'',conversion:'1',saleRateMinor:100,purchaseRateMinor:50,saleRateUnit:'PCS',purchaseRateUnit:'PCS',lowStock:'1',quantity:'10',importUnit:'PCS'};
assert.equal(backend.post('importStock',{id:'sync-stock-opening00001',openingDate:'2026-01-01',items:[item]}).ok,true);
const browser=await chromium.launch({headless:true,args:['--no-sandbox']}),context=await browser.newContext({viewport:{width:1440,height:1000},serviceWorkers:'block'});
await context.addInitScript(endpoint=>{localStorage.setItem('rf.endpoint',JSON.stringify(endpoint));localStorage.setItem('rf.connectionInfo',JSON.stringify({endpoint,version:'1.24.0'}));window.onlineForTest=true;Object.defineProperty(navigator,'onLine',{configurable:true,get:()=>window.onlineForTest});},endpoint);
let failReads=false;
await context.route('https://script.google.com/**',async route=>{const body=route.request().postDataJSON();if(failReads&&body.action==='listAccounts'){await route.fulfill({json:{ok:false,error:'Test refresh unavailable'}});return;}await route.fulfill({json:backend.post(body.action,body.transaction)});});
const page=await context.newPage();page.setDefaultTimeout(12000);page.on('pageerror',error=>errors.push(error.message));page.on('dialog',dialog=>dialog.accept());
const status=()=>page.locator('.topbar .sync-status'),toggle=()=>status().locator('summary');
try{
 await page.goto(process.env.LEDGER_TEST_URL||'http://127.0.0.1:5175');await toggle().filter({hasText:'Up to date'}).waitFor();await mkdir('/tmp/ledger-browser-results',{recursive:true});for(const width of [1440,1024,768,390,320]){await page.setViewportSize({width,height:900});await page.locator('.balance-card h2').evaluateAll(elements=>elements.forEach((el,i)=>el.textContent=['₹39,887.50','₹28,936.97','₹68,824.47','₹15,30,691.32'][i]));await page.screenshot({path:`/tmp/ledger-browser-results/dashboard-layout-${width}.png`,fullPage:true});const layout=await page.evaluate(()=>({scroll:document.documentElement.scrollWidth,viewport:innerWidth,header:[...document.querySelector('.topbar').children].map(el=>el.getBoundingClientRect().toJSON()),title:document.querySelector('.dashboard-heading h1').getBoundingClientRect().toJSON(),actions:document.querySelector('.dashboard-actions').getBoundingClientRect().toJSON(),balanceWidth:document.querySelector('.current-balance-grid').clientWidth,balanceColumns:getComputedStyle(document.querySelector('.current-balance-grid')).gridTemplateColumns.split(' ').length}));assert.ok(layout.scroll<=layout.viewport,`Dashboard overflows at ${width}px`);for(let i=1;i<layout.header.length;i++)assert.ok(layout.header[i].left>=layout.header[i-1].right+4,`Header controls collide at ${width}px`);assert.ok(layout.title.bottom<=layout.actions.top+1||layout.title.right<=layout.actions.left,`Dashboard title overlaps actions at ${width}px`);assert.equal(layout.balanceColumns,layout.balanceWidth>=760?4:2);const amounts=await page.locator('.balance-card h2').evaluateAll(elements=>elements.map(el=>{const range=document.createRange();range.selectNodeContents(el);const lines=[...range.getClientRects()];return {lines:lines.length,fits:el.scrollWidth<=el.clientWidth};}));assert.ok(amounts.every(amount=>amount.lines===1&&amount.fits),`Balance amounts wrap or overflow at ${width}px`);}await page.setViewportSize({width:1440,height:1000});assert.equal(await page.locator('main>.sync-status, main>.cache-status, .connection').count(),0);assert.equal(await page.getByText('Invoices and payments show confirmed data unless marked as pending.',{exact:true}).count(),0);
 await toggle().click();await status().getByText(/Last confirmed/).waitFor();await page.keyboard.press('Escape');assert.equal(await status().locator('details').getAttribute('open'),null);assert.equal(await toggle().evaluate(el=>el===document.activeElement),true);await page.keyboard.press('Enter');await status().getByRole('button',{name:'Refresh records',exact:true}).waitFor();await page.getByRole('heading',{name:'Dashboard',exact:true}).click();assert.equal(await status().locator('details').getAttribute('open'),null);
 failReads=true;await page.locator('.period-bar .refresh').click();await toggle().filter({hasText:'Sync needs attention'}).waitFor();assert.equal(await page.locator('main>div>.error,main>.error').count(),0);await toggle().click();await status().getByText('Test refresh unavailable',{exact:true}).waitFor();failReads=false;await status().getByRole('button',{name:'Refresh records',exact:true}).click();await toggle().filter({hasText:'Up to date'}).waitFor();assert.equal(await status().getByText('Test refresh unavailable',{exact:true}).count(),0);await page.keyboard.press('Escape');
 await page.evaluate(()=>{window.onlineForTest=false;window.dispatchEvent(new Event('offline'));});await toggle().filter({hasText:'Offline'}).waitFor();await page.evaluate(()=>{window.onlineForTest=true;window.dispatchEvent(new Event('online'));});await toggle().filter({hasText:'Up to date'}).waitFor();
 // A successful party save uses a dismissible toast rather than a page banner.
 await page.locator('.sidebar').getByRole('button',{name:/Parties/}).click();await page.getByRole('button',{name:/Add Party/}).click();const partyDialog=page.locator('.account-party-dialog');await partyDialog.getByLabel('Name',{exact:true}).fill('Toast customer');await partyDialog.getByRole('button',{name:'Save party',exact:true}).click();await partyDialog.waitFor({state:'hidden'});await page.locator('.feedback-toast').getByText('Party saved.',{exact:true}).waitFor();await page.getByRole('button',{name:'Dismiss notification',exact:true}).click();await page.locator('.feedback-toast').waitFor({state:'detached'});
 // Mobile popover stays within the viewport.
 await page.setViewportSize({width:320,height:700});await toggle().click();await status().getByRole('button',{name:'Refresh records',exact:true}).waitFor();assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);const bounds=await status().locator('.sync-popover').boundingBox();assert.ok(bounds.x>=0&&bounds.x+bounds.width<=320);await mkdir('/tmp/ledger-browser-results',{recursive:true});await page.screenshot({path:'/tmp/ledger-browser-results/sync-mobile.png',fullPage:true});await page.keyboard.press('Escape');
 // Durable stock writes participate in the same compact indicator and expose recovery.
 const second=await browser.newContext({viewport:{width:1440,height:1000},serviceWorkers:'block'});await second.addInitScript(({endpoint,item,date})=>{localStorage.setItem('rf.endpoint',JSON.stringify(endpoint));localStorage.setItem('rf.connectionInfo',JSON.stringify({endpoint,version:'1.24.0'}));localStorage.setItem('rf.stock-pending:'+endpoint,JSON.stringify({queue:[1,2].map(n=>({action:'recordStock',payload:{id:'sync-stock-save0000000'+n,stockMovementSchemaVersion:1,movementDate:date,reason:'Sync test',movements:[{stockItemId:item.id,expectedRevision:0,quantity:'-1',unit:'PCS'}]}}))}));},{endpoint,item,date});
 let release,first=true,failWrites=true;const gate=new Promise(resolve=>release=resolve);await second.route('https://script.google.com/**',async route=>{const body=route.request().postDataJSON();if(body.action==='recordStock'&&first){first=false;await gate;}if(body.action==='recordStock'&&failWrites){await route.abort('failed');return;}await route.fulfill({json:backend.post(body.action,body.transaction)});});const pendingPage=await second.newPage();pendingPage.on('pageerror',error=>errors.push(error.message));await pendingPage.goto('http://127.0.0.1:5175');await pendingPage.locator('.sync-status summary').filter({hasText:'Saving 2 changes'}).waitFor();release();await pendingPage.locator('.sync-status summary').filter({hasText:'Sync needs attention'}).waitFor();await pendingPage.locator('.sync-status summary').click();await pendingPage.getByRole('button',{name:'Review stock upload',exact:true}).click();await pendingPage.getByRole('heading',{name:'Stock',exact:true}).waitFor();failWrites=false;await pendingPage.getByRole('button',{name:'Retry stock update',exact:true}).click();await pendingPage.locator('.sync-status summary').filter({hasText:'Up to date'}).waitFor();assert.equal(backend.post('listStock',{}).items[0].balance,'8');await second.close();assert.deepEqual(errors,[]);console.log(JSON.stringify({passed:true,scenarios:'compact status, outside click, keyboard dismissal, read error recovery, offline state, mobile bounds, stock queue and retry',errors}));
}finally{await browser.close();}
