import assert from 'node:assert/strict';
import {readFile,mkdir} from 'node:fs/promises';
import {accountBackend,TEST_ACCESS_TOKEN} from '../helpers/accountBackend.js';
const {chromium}=await import(process.env.PLAYWRIGHT_MODULE||'playwright');
const backend=accountBackend(),endpoint='https://script.google.com/macros/s/TEST-ONLY/exec',errors=[],calls=[];
const browser=await chromium.launch({executablePath:process.env.PLAYWRIGHT_EXECUTABLE_PATH||undefined,headless:true,args:['--no-sandbox']}),context=await browser.newContext({viewport:{width:1440,height:1000},serviceWorkers:'block'});
await context.addInitScript(({endpoint,token})=>{localStorage.setItem('rf.endpoint',JSON.stringify(endpoint));localStorage.setItem('rf.connectionInfo',JSON.stringify({endpoint,version:'1.27.0'}));sessionStorage.setItem('rf.access-token:'+endpoint,token);window.print=()=>{if(window.parent!==window){window.parent.__printedReport=document.documentElement.outerHTML;window.dispatchEvent(new Event('afterprint'));}};},{endpoint,token:TEST_ACCESS_TOKEN});
await context.route('https://script.google.com/**',route=>{const body=route.request().postDataJSON();calls.push(body.action);return route.fulfill({json:backend.rawPost(body)});});
const page=await context.newPage();page.setDefaultTimeout(15000);page.on('pageerror',error=>errors.push(error.message));
const field=name=>page.getByLabel(name,{exact:true});
async function ready(count){await page.waitForFunction(count=>[...document.querySelectorAll('.cutting-metrics>div')].some(el=>el.textContent===`Panels fitted${count}`),count);await page.waitForFunction(()=>!document.querySelector('.cutting-toolbar button[data-hotkey="alt+d"]')?.disabled);}
try{
 await page.goto(process.env.LEDGER_TEST_URL||'http://127.0.0.1:5175');await page.keyboard.press('Alt+Shift+6');await page.getByRole('heading',{name:'Tools',exact:true}).waitFor();assert.equal(await field('Allow panel rotation').isChecked(),true);
 await field('Panel sizes').fill('24x32x2,32x32x5,30x12');await field('Available sheet sizes').fill('48x96,48x120');await ready('8 / 8');assert.ok(await page.locator('.cutting-diagram svg').count()>0);
 await field('Panel sizes').fill('24x32x3,32x32x5,30x12');await ready('9 / 9');await page.locator('.cutting-details summary').first().click();await page.getByText(/Cut order · coordinates/).first().waitFor();
 await mkdir('/tmp/ledger-browser-results',{recursive:true});await page.screenshot({path:'/tmp/ledger-browser-results/tools-desktop.png',fullPage:true});
 const downloadEvent=page.waitForEvent('download');await page.getByRole('button',{name:/Download report/}).click();const download=await downloadEvent,html=await readFile(await download.path(),'utf8');assert.ok(html.includes('<svg'));assert.ok(html.includes('Cut order'));assert.ok(!html.includes(endpoint)&&!html.includes(TEST_ACCESS_TOKEN));
 await page.getByRole('button',{name:/Print \/ Save PDF/}).click();await page.waitForFunction(()=>window.__printedReport?.includes('<svg'));assert.ok((await page.evaluate(()=>window.__printedReport)).includes('Requested panels'));
 await field('Panel size unit').selectOption('mm');await field('Sheet size unit').selectOption('mm');await field('Cutter width').fill('0');await field('Panel sizes').fill('70x40');await field('Available sheet sizes').fill('40x80');await ready('1 / 1');await field('Allow panel rotation').uncheck();await ready('0 / 1');await page.getByText('1 panel(s) could not be placed.',{exact:true}).waitFor();await field('Allow panel rotation').check();await ready('1 / 1');
 await field('Panel sizes').fill('40x40x3');await field('Available sheet sizes').fill('40x40x2');await page.getByLabel('Use available quantities').check();await ready('2 / 3');await page.getByLabel('Use available quantities').uncheck();await ready('3 / 3');
 await field('Panel sizes').fill('40x40x2');await field('Available sheet sizes').fill('40x40,100x50');await field('Optimization goal').selectOption('waste');await ready('2 / 2');assert.equal(await page.locator('.cutting-metrics>div').first().innerText(),'Sheets\n2');await field('Optimization goal').selectOption('sheets');await page.waitForFunction(()=>document.querySelector('.cutting-metrics>div')?.textContent==='Sheets1');await ready('2 / 2');
 await field('Cutter width').fill('3');await field('Panel sizes').fill('24x96x2');await field('Available sheet sizes').fill('48x96');await field('Allow panel rotation').uncheck();await ready('2 / 2');assert.equal(await page.locator('.cutting-metrics>div').first().innerText(),'Sheets\n2');
 await field('Panel sizes').fill('20x20x600');await page.waitForTimeout(400);await field('Panel sizes').fill('24x96');await ready('1 / 1');
 await field('Panel sizes').fill('24x96x0');await page.getByRole('alert').filter({hasText:'quantity must'}).waitFor();assert.equal(await page.getByRole('button',{name:/Download report/}).isDisabled(),true);await field('Panel sizes').fill('24x96');await ready('1 / 1');
 await page.keyboard.press('Alt+Shift+1');await page.getByRole('heading',{name:'Dashboard',exact:true}).waitFor();await page.keyboard.press('Alt+Shift+6');await page.getByRole('heading',{name:'Tools',exact:true}).waitFor();assert.equal(await field('Panel sizes').inputValue(),'24x96');await ready('1 / 1');
 await field('Panel size unit').selectOption('ft');await field('Sheet size unit').selectOption('ft');await field('Cutter width unit').selectOption('soot');await field('Cutter width').fill('1');await field('Panel sizes').fill('2ft 3in 2soot x 4ft x 2');await field('Available sheet sizes').fill('4x8');await ready('2 / 2');
 const sootDownloadEvent=page.waitForEvent('download');await page.getByRole('button',{name:/Download report/}).click();const sootDownload=await sootDownloadEvent;assert.ok((await readFile(await sootDownload.path(),'utf8')).includes('Cutter width 1 soot'));
 await field('Panel sizes').fill('4ft x 8ft x 12');await ready('12 / 12');
 const allSheetsDownloadEvent=page.waitForEvent('download');await page.getByRole('button',{name:/Download report/}).click();const allSheetsDownload=await allSheetsDownloadEvent;assert.ok((await readFile(await allSheetsDownload.path(),'utf8')).includes('Sheet 12 ·'),'Reports must retain every sheet');
 const inputsBox=await page.locator('.tools-page[aria-label="Sheet cutting"] .cutting-inputs').boundingBox();
 assert.equal(await page.locator('.cutting-diagram svg').count(),1,'Show one selected sheet rather than a long diagram list');
 await page.getByRole('button',{name:'Sheet 12',exact:false}).click();await page.getByRole('heading',{name:/Sheet 12/}).waitFor();
 assert.deepEqual(await page.locator('.tools-page[aria-label="Sheet cutting"] .cutting-inputs').boundingBox(),inputsBox,'Switching sheets must not move settings');
 await page.getByRole('button',{name:'Sheet 1',exact:false}).first().click();await page.getByRole('heading',{name:/Sheet 1 /}).waitFor();
 await page.screenshot({path:'/tmp/ledger-browser-results/tools-desktop.png',fullPage:true});
 await page.setViewportSize({width:1024,height:768});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);assert.equal(await field('Panel sizes').isVisible(),true);assert.equal(await page.locator('.tools-page[aria-label="Sheet cutting"] .cutting-results').isVisible(),true);
 await page.setViewportSize({width:390,height:844});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
 assert.equal(await field('Panel sizes').isVisible(),true);assert.equal(await page.locator('.tools-page[aria-label="Sheet cutting"] .cutting-results').isVisible(),false);
 await page.screenshot({path:'/tmp/ledger-browser-results/tools-mobile-setup.png',fullPage:true});
 await page.getByRole('button',{name:'View cutting plan'}).click();assert.equal(await field('Panel sizes').isVisible(),false);assert.equal(await page.locator('.tools-page[aria-label="Sheet cutting"] .cutting-results').isVisible(),true);
 assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
 await page.getByRole('button',{name:'Sheet 12',exact:false}).click();await page.getByRole('heading',{name:/Sheet 12/}).waitFor();
 await page.screenshot({path:'/tmp/ledger-browser-results/tools-mobile.png',fullPage:true});
 await page.getByRole('button',{name:'Sizes & settings',exact:true}).click();await field('Panel sizes').waitFor({state:'visible'});assert.equal(await field('Panel sizes').inputValue(),'4ft x 8ft x 12');
 await page.getByRole('button',{name:'Cutting plan 12',exact:true}).click();assert.equal(await page.locator('.tools-page[aria-label="Sheet cutting"] .cutting-results').isVisible(),true);
 await page.emulateMedia({media:'print'});assert.equal(await page.locator('.report-view').evaluate(el=>getComputedStyle(el).display),'none');await page.emulateMedia({media:'screen'});
 await page.getByRole('button',{name:'Laminate calculator',exact:true}).click();
 const laminate=page.getByRole('region',{name:'Laminate calculator',exact:true});
 await field('Laminate panel unit').selectOption('ft');await field('Laminate panel sizes').fill('2x4x3');await field('Surface coverage').selectOption('2');await field('Price per sheet (₹)').fill('1250.50');
 await laminate.getByRole('button',{name:'View material estimate'}).click();assert.equal(await field('Laminate panel sizes').isVisible(),false);
 assert.equal(await laminate.locator('.laminate-metrics>div').nth(0).innerText(),'Net coverage\n48 sq ft');
 assert.equal(await laminate.locator('.laminate-metrics>div').nth(1).innerText(),'With waste\n52.8 sq ft');
 assert.equal(await laminate.locator('.laminate-metrics>div').nth(2).innerText(),'Sheets by area\n2');
 assert.equal(await laminate.locator('.laminate-metrics>div').nth(3).innerText(),'Sheet cost\n₹2,501.00');
 assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
 await page.screenshot({path:'/tmp/ledger-browser-results/laminate-mobile.png',fullPage:true});
 const laminateDownloadEvent=page.waitForEvent('download');await laminate.getByRole('button',{name:'Download report',exact:true}).click();const laminateDownload=await laminateDownloadEvent,laminateHtml=await readFile(await laminateDownload.path(),'utf8');
 assert.ok(laminateHtml.includes('Both faces')&&laminateHtml.includes('52.8')&&laminateHtml.includes('₹2,501.00'));assert.ok(!laminateHtml.includes(endpoint)&&!laminateHtml.includes(TEST_ACCESS_TOKEN));
 await laminate.getByRole('button',{name:'Print / Save PDF',exact:true}).click();await page.waitForFunction(()=>window.__printedReport?.includes('Laminate estimate'));
 await laminate.getByRole('button',{name:'Coverage & settings',exact:true}).click();await field('Waste allowance (%)').fill('-1');await laminate.getByRole('alert').filter({hasText:'Waste allowance'}).waitFor();assert.equal(await laminate.getByRole('button',{name:'View material estimate'}).isDisabled(),true);
 await field('Waste allowance (%)').fill('10');await field('Laminate panel sizes').fill('5x5');await laminate.getByRole('button',{name:'View material estimate'}).click();await laminate.getByRole('alert').filter({hasText:'do not fit'}).waitFor();await laminate.getByRole('button',{name:'Coverage & settings',exact:true}).click();
 await field('Laminate panel sizes').fill('2x4x3');await page.setViewportSize({width:1440,height:1000});await page.screenshot({path:'/tmp/ledger-browser-results/laminate-desktop.png',fullPage:true});
 await page.getByRole('button',{name:'Sheet cutting',exact:true}).click();assert.equal(await field('Panel sizes').inputValue(),'4ft x 8ft x 12');
 await page.getByRole('button',{name:'Laminate calculator',exact:true}).click();assert.equal(await field('Laminate panel sizes').inputValue(),'2x4x3');
 assert.deepEqual(errors,[]);assert.ok(calls.every(action=>['listAccounts','listStock','getInvoices','list'].includes(action)),'Tools must not write to the Sheet');console.log(JSON.stringify({passed:true,scenarios:'live updates, rotation, kerf, goals, finite quantities, cancelled jobs, validation, diagrams, report download, print, navigation persistence, desktop sheet navigation, mobile setup/plan tabs, laminate faces/waste/price, oversize warnings, laminate reports, tool draft persistence, no remote writes',calls}));
}finally{await browser.close();}
