import test from 'node:test';
import assert from 'node:assert/strict';
import {planBulkDelete} from '../src/bulkDelete.js';
import {accountBackend} from './helpers/accountBackend.js';
import {makeParty,makeInvoice,makeInvoiceNote,invoiceNoteRevision} from '../src/accounts.js';
import {makeTransaction} from '../src/ledger.js';
function fixture(){const backend=accountBackend();const party=makeParty({name:'Bulk customer',phone:'',address:'',openingDate:'2026-01-01',openingBalance:'0'},'bulk-party-000000000001');backend.post('createParty',party);const invoice=backend.post('createInvoice',makeInvoice({partyId:party.id,type:'sale',invoiceDate:'2026-09-01',notes:'',items:[{description:'Chair',quantity:'1',rate:'100',discount:'0',cost:'60'}]},'bulk-invoice-0000000001')).record;const debit=backend.post('createInvoiceNote',makeInvoiceNote({type:'debit',effect:'return',cost:'10',amount:'50',noteDate:'2026-09-02',reason:'Charge'},invoice,'bulk-debit-000000000001')).record;const credit=backend.post('createInvoiceNote',makeInvoiceNote({type:'credit',effect:'return',cost:'65',amount:'130',noteDate:'2026-09-02',reason:'Return'},invoice,'bulk-credit-00000000001')).record;return {backend,invoice,debit,credit};}
test('bulk note deletion plans dependent credit before debit and preserves valid intermediate totals',()=>{const {backend,debit,credit}=fixture();const plan=planBulkDelete([{kind:'note',record:debit},{kind:'note',record:credit}],backend.post('listAccounts',{}),'Bulk correction');assert.deepEqual(plan.map(op=>op.payload.id),[credit.id,debit.id]);for(const op of plan){assert.equal(backend.post(op.action,op.payload).ok,true);assert.equal(backend.post('listAccounts',{}).ok,true);}assert.equal(backend.tabs.get('InvoiceNotes').data.length,3);});
test('bulk invoice deletion covers selected attached notes once and rejects stale records and notes',()=>{const {backend,invoice,credit}=fixture();const snapshot=backend.post('listAccounts',{});const selection=[{kind:'invoice',record:invoice,expectedNotes:invoiceNoteRevision(snapshot.notes,invoice.id)},{kind:'note',record:credit}];assert.equal(planBulkDelete(selection,snapshot,'Bulk').length,1);assert.throws(()=>planBulkDelete([{kind:'invoice',record:{...invoice,revision:1}}],snapshot,'Bulk'),/changed/);assert.throws(()=>planBulkDelete([{...selection[0],expectedNotes:''}],snapshot,'Bulk'),/notes changed/);});
test('unsafe partial note selections are refused before queueing and stale payment deletions are rejected',()=>{const {backend,debit}=fixture();assert.throws(()=>planBulkDelete([{kind:'note',record:debit}],backend.post('listAccounts',{}),'Bulk'),/safe order/);const payment=makeTransaction({category:'Sale',direction:'in',method:'Cash',amount:'10',party:'Customer',notes:'',dateTime:'2026-09-02T12:00'},'bulk-payment-0000000001');backend.post('create',payment);assert.equal(backend.post('deletePayment',{id:payment.id,_expectedRevision:1}).code,'EDIT_CONFLICT');assert.equal(backend.post('deletePayment',{id:payment.id,_expectedRevision:0,reason:'Bulk removal'}).ok,true);assert.equal(backend.post('listDeleted',{}).transactions.find(record=>record.id===payment.id).deleteReason,'Bulk removal');assert.equal(backend.post('delete',{id:payment.id,_expectedRevision:0}).ok,true);});
