import test from 'node:test';
import assert from 'node:assert/strict';
import {accountBackend} from './helpers/accountBackend.js';
import {stockDecimal,stockText,convertStock,parseStockCsv,stockInvoiceStatus} from '../src/stock.js';
import {makeParty,makeInvoice} from '../src/accounts.js';
const itemId='stock-item-0000000000001',openingId='opening-stock-00000000001',partyId='stock-party-000000000001',invoiceId='stock-invoice-0000000001';
const item=(extra={})=>({id:itemId,sourceId:'mybillbook-model-1',name:'SCREW',code:'MODEL-1',baseUnit:'PCS',secondaryUnit:'BOX',conversion:'1000',quantity:'6.988',importUnit:'BOX',saleRateUnit:'PCS',purchaseRateUnit:'BOX',saleRateMinor:100,purchaseRateMinor:80,lowStock:'100',...extra});
function opening(b,items=[item()]){const result=b.post('importStock',{id:openingId,openingDate:'2026-10-01',items});assert.equal(result.ok,true,result.error);return result.stock;}
function invoice(b,type='sale',id=invoiceId){b.post('createParty',makeParty({name:'Stock customer',phone:'',address:'',openingDate:'2026-01-01',openingBalance:'0'},partyId));const payload=makeInvoice({partyId,type,invoiceDate:'2026-10-05',notes:'',items:[{description:'SCREW',quantity:'2',rate:'100',cost:'50',discount:'0'},{description:'MADE TO ORDER',quantity:'1',rate:'100',cost:'50',discount:'0'}]},id);const result=b.post('createInvoice',payload);assert.equal(result.ok,true,result.error);return result.record;}
const read=b=>b.post('listStock',{});
function review(record,extra={}){return {id:'stock-review-00000000001',invoiceId:record.id,invoiceRevision:0,movementDate:'2026-10-05',entries:[{invoiceItemId:record.items[0].id,status:'updated',reason:'Used for order',movements:[{stockItemId:itemId,quantity:'2',unit:'BOX'}]},{invoiceItemId:record.items[1].id,status:'no-impact',reason:'Made to order',movements:[]}],...extra};}
test('stock decimals preserve CSV precision and convert boxes and grams exactly',()=>{assert.equal(convertStock('6.988','1000'),'6988');assert.equal(convertStock('2750','0.001'),'2.75');assert.equal(stockText(stockDecimal('10.15384615')),'10.15384615');assert.throws(()=>stockDecimal('1e3'));assert.throws(()=>stockDecimal('0.000000001'));assert.throws(()=>convertStock('0.00000001','0.001'));});
test('CSV finds headers after instruction rows, parses quoted names, excludes Generic Sale and applies confirmed door groups',()=>{const csv='Instructions\n\nItem ID,"Item Name*\n(mandatory field)",Item code,Current stock,Sales Price,Purchase Price,Low stock alert quantity\na,"DOOR, WHITE",MODEL-1,6.988,100,80,1\nb,GENERIC SALE,,-612.03,0,0,\nc,DOOR,MODEL-2,2,200,100,\n';const rows=parseStockCsv(csv);assert.equal(rows.length,3);assert.equal(rows[0].name,'DOOR, WHITE');assert.equal(rows[0].quantity,'6.988');assert.equal(rows[0].baseUnit,'NOS');assert.equal(rows[1].include,false);assert.equal(rows[2].code,'MODEL-2');assert.throws(()=>parseStockCsv(csv+'a,DUPLICATE,,1,1,1,\n'),/duplicate/);});
test('opening stock is idempotent, preserves variants and does not change money or parties',()=>{const b=accountBackend(),items=[item(),item({id:'stock-item-0000000000002',sourceId:'mybillbook-model-2',code:'MODEL-2',quantity:'2'})];const data=opening(b,items);assert.equal(data.items.length,2);assert.equal(data.items[0].balance,'6988');assert.equal(b.post('importStock',{id:openingId,openingDate:'2026-10-01',items}).ok,true);assert.equal(read(b).movements.length,2);assert.equal(b.post('listAccounts',{}).invoices.length,0);assert.equal(b.post('listAccounts',{}).transactions.length,0);assert.equal(b.post('listAccounts',{}).parties.length,0);assert.equal(b.post('importStock',{id:'opening-stock-00000000002',openingDate:'2026-10-01',items}).ok,false);});
test('invalid opening quantities, missing units and duplicate models are rejected before import',()=>{for(const items of [[item({quantity:'-1'})],[item({baseUnit:''})],[item({name:'GENERIC SALE'})],[item(),item({id:'stock-item-0000000000002',sourceId:'another-source'})]]){const b=accountBackend(),result=b.post('importStock',{id:openingId,openingDate:'2026-10-01',items});assert.equal(result.ok,false);assert.equal(result.code,'STOCK_REJECTED');assert.equal(read(b).items.length,0);assert.equal(read(b).movements.length,0);}});
test('interrupted opening remains invisible and retry finishes once',()=>{for(const tab of ['StockMovements','StockOperations']){const b=accountBackend();b.failNext(tab);const payload={id:openingId,openingDate:'2026-10-01',items:[item()]};assert.equal(b.post('importStock',payload).ok,false);assert.equal(read(b).items.length,0);assert.equal(read(b).movements.length,0);assert.equal(b.post('importStock',payload).ok,true);assert.equal(read(b).items.length,1);assert.equal(read(b).items[0].balance,'6988');assert.equal(read(b).movements.length,1);}});
test('sale review removes stock, no-impact items are marked and retry cannot deduct twice',()=>{const b=accountBackend();opening(b);const record=invoice(b),payload=review(record);const result=b.post('reviewInvoiceStock',payload);assert.equal(result.ok,true,result.error);assert.equal(result.stock.items[0].balance,'4988');assert.equal(stockInvoiceStatus(record,result.stock.reviews,result.stock.operations),'Reviewed');assert.equal(b.post('reviewInvoiceStock',payload).ok,true);assert.equal(read(b).items[0].balance,'4988');assert.equal(b.post('reviewInvoiceStock',{...payload,id:'stock-review-00000000002'}).ok,false);assert.equal(read(b).items[0].balance,'4988');assert.equal(b.post('listAccounts',{}).invoices[0].totalMinor,30000);});
test('purchase review adds stock using the secondary unit',()=>{const b=accountBackend();opening(b);const record=invoice(b,'purchase'),result=b.post('reviewInvoiceStock',review(record));assert.equal(result.ok,true,result.error);assert.equal(result.stock.items[0].balance,'8988');});
test('partial review leaves other items pending and accepts the remaining item once',()=>{const b=accountBackend();opening(b);const record=invoice(b),payload=review(record);payload.entries=payload.entries.slice(0,1);assert.equal(b.post('reviewInvoiceStock',payload).ok,true);assert.equal(stockInvoiceStatus(record,read(b).reviews,read(b).operations),'Partially updated');const remaining={...review(record),id:'stock-review-00000000002',entries:review(record).entries.slice(1)};assert.equal(b.post('reviewInvoiceStock',remaining).ok,true);assert.equal(stockInvoiceStatus(record,read(b).reviews,read(b).operations),'Reviewed');});
test('negative stock needs explicit approval and concurrent review of the same invoice item is rejected',()=>{const b=accountBackend();opening(b);const record=invoice(b),payload=review(record);payload.entries[0].movements[0].quantity='10';assert.equal(b.post('reviewInvoiceStock',payload).ok,false);assert.equal(read(b).items[0].balance,'6988');assert.equal(b.post('reviewInvoiceStock',{...payload,allowNegative:true}).ok,true);assert.equal(read(b).items[0].balance,'-3012');assert.equal(b.post('reviewInvoiceStock',{...payload,id:'stock-review-00000000002',allowNegative:true}).ok,false);});
test('interrupted review staging does not affect stock and retries commit once',()=>{const b=accountBackend();opening(b);const record=invoice(b),payload=review(record);b.failNext('StockOperations');assert.equal(b.post('reviewInvoiceStock',payload).ok,false);assert.equal(read(b).items[0].balance,'6988');assert.equal(read(b).reviews.length,0);assert.equal(b.post('reviewInvoiceStock',payload).ok,true);assert.equal(read(b).items[0].balance,'4988');assert.equal(read(b).reviews.length,2);});
test('reversal restores stock, releases reviews and is idempotent',()=>{const b=accountBackend();opening(b);const record=invoice(b),payload=review(record);b.post('reviewInvoiceStock',payload);const reverse={id:'stock-reversal-000000001',reversesId:payload.id,movementDate:'2026-10-06',reason:'Wrong material'};assert.equal(b.post('reverseStock',reverse).ok,true);assert.equal(read(b).items[0].balance,'6988');assert.equal(read(b).reviews.length,0);assert.equal(b.post('reverseStock',reverse).ok,true);assert.equal(read(b).items[0].balance,'6988');assert.equal(b.post('reverseStock',{...reverse,id:'stock-reversal-000000002'}).ok,false);assert.equal(b.post('reviewInvoiceStock',{...payload,id:'stock-review-00000000002'}).ok,true);assert.equal(read(b).items[0].balance,'4988');});
test('edited invoices require reversal before applying new stock movements',()=>{const b=accountBackend();opening(b);const record=invoice(b),payload=review(record);b.post('reviewInvoiceStock',payload);const next=makeInvoice({partyId,type:'sale',invoiceDate:'2026-10-05',notes:'',items:[{description:'NEW ITEM',quantity:'1',rate:'100',cost:'50',discount:'0'}]},invoiceId);const updated=b.post('updateInvoice',{...next,invoiceNumber:record.invoiceNumber,_expectedRevision:0,_editId:'stock-invoice-edit-0000001'});assert.equal(updated.ok,true,updated.error);const latest=b.post('getInvoices',{ids:[invoiceId]}).invoices[0];assert.equal(stockInvoiceStatus(latest,read(b).reviews,read(b).operations),'Needs review');const newReview={...payload,id:'stock-review-00000000002',invoiceRevision:1,entries:[{...payload.entries[0],invoiceItemId:latest.items[0].id}]};assert.equal(b.post('reviewInvoiceStock',newReview).ok,false);b.post('reverseStock',{id:'stock-reversal-000000001',reversesId:payload.id,movementDate:'2026-10-06',reason:'Invoice changed'});assert.equal(b.post('reviewInvoiceStock',newReview).ok,true);assert.equal(read(b).items[0].balance,'4988');});
test('KG stock uses exact decimals and conversion snapshots remain in movements',()=>{const b=accountBackend();opening(b,[item({baseUnit:'KG',secondaryUnit:'GRAM',conversion:'0.001',quantity:'25',importUnit:'KG',saleRateUnit:'KG',purchaseRateUnit:'KG'})]);const payload={id:'stock-manual-00000000001',stockItemId:itemId,quantity:'-2750',unit:'GRAM',movementDate:'2026-10-05',reason:'Material used'};assert.equal(b.post('recordStock',payload).ok,true);assert.equal(read(b).items[0].balance,'22.25');assert.equal(read(b).movements[1].conversion,'0.001');assert.equal(b.post('recordStock',payload).ok,true);assert.equal(read(b).items[0].balance,'22.25');});
test('invalid unit, old dates, changed request IDs and foreign invoice items cannot move stock',()=>{const b=accountBackend();opening(b);const record=invoice(b);for(const payload of [{...review(record),invoiceRevision:1},{...review(record),movementDate:'2026-09-30'},{...review(record),entries:[{...review(record).entries[0],invoiceItemId:'foreign'}]}])assert.equal(b.post('reviewInvoiceStock',payload).ok,false);assert.equal(read(b).items[0].balance,'6988');assert.equal(b.post('recordStock',{id:'stock-manual-00000000001',stockItemId:itemId,quantity:'1',unit:'KG',movementDate:'2026-10-05',reason:'Wrong unit'}).ok,false);b.post('reviewInvoiceStock',review(record));assert.equal(b.post('reviewInvoiceStock',{...review(record),allowNegative:true}).ok,false);});
test('stock reads never create tabs and new items start at zero',()=>{const b=accountBackend();assert.equal(read(b).ok,true);assert.equal(b.tabs.size,0);opening(b);const newItem=item({id:'stock-item-0000000000002',sourceId:'',code:'MODEL-2'});const result=b.post('createStockItem',{id:'stock-new-item-0000000001',item:newItem});assert.equal(result.ok,true,result.error);assert.equal(result.stock.items.find(row=>row.id===newItem.id).balance,'0');});

test('owner-confirmed units prefill only matching source IDs and preserve stock decimals and confirmed price units',async()=>{
 const {confirmedMyBillBookUnits,applyConfirmedStockUnits}=await import('../src/stockImportProfile.js');
 const ids=Object.keys(confirmedMyBillBookUnits).slice(0,4),csv='Item ID,Item Name*,Current stock,Sales Price,Purchase Price\n'+ids.map((id,i)=>`${id},CONFIRMED ITEM ${i},${['574.09','472.83','85.53','6.988'][i]},350,260`).join('\n');
 const rows=parseStockCsv(csv);
 assert.deepEqual(rows.slice(0,3).map(row=>row.baseUnit),['KG','KG','KG']);assert.deepEqual(rows.slice(0,3).map(row=>row.quantity),['574.09','472.83','85.53']);
 assert.equal(rows[3].baseUnit,'PCS');assert.equal(rows[3].importUnit,'BOX');assert.equal(convertStock(rows[3].quantity,rows[3].conversion),'6988');assert.ok(rows.every(row=>row.saleRateUnit===row.importUnit&&row.purchaseRateUnit===row.importUnit));
 const changed={...rows[3],conversion:'500'};assert.deepEqual(applyConfirmedStockUnits(changed),changed);const unrelated={...rows[3],sourceId:'unrelated-id',baseUnit:'',importUnit:'',secondaryUnit:'',conversion:''};assert.deepEqual(applyConfirmedStockUnits(unrelated),unrelated);
});


test('confirmed bearings and lock packages convert exported fractions into whole pieces',async()=>{
 const {applyConfirmedStockUnits}=await import('../src/stockImportProfile.js');
 const cases=[['13606a1b-437b-4d9b-b535-2dc9281bb408','0.44','PACKET','110'],['d832ba5d-1e6b-4d13-9ca1-d84df520f6ec','11.4','BOX','228'],['5ae29610-e9be-4ffe-b0f7-1192585052f0','1.45','BOX','29']];
 for(const [sourceId,quantity,unit,expected] of cases){const row=applyConfirmedStockUnits({sourceId,quantity,baseUnit:'',importUnit:'',secondaryUnit:'',conversion:'',saleRateUnit:'',purchaseRateUnit:''});assert.equal(row.baseUnit,'PCS');assert.equal(row.importUnit,unit);assert.equal(convertStock(row.quantity,row.conversion),expected);assert.equal(row.saleRateUnit,unit);assert.equal(row.purchaseRateUnit,unit);}
});

test('confirmed bori and PVC packages convert accurately and fractional pieces require review',async()=>{
 const {applyConfirmedStockUnits}=await import('../src/stockImportProfile.js');const {validateStockBaseQuantity}=await import('../src/stock.js');
 const cases=[['d1d287a0-b77d-4f94-9c0d-a736ed1b1ec2','4.09','BORI','818'],['ee32450c-8183-410f-a772-99a03316ba90','2.5','PACKET','75'],['ec2d7a2c-4910-41f3-b459-9a5b9e239cf4','5.36','PACKET','268']];
 for(const [sourceId,quantity,unit,expected] of cases){const row=applyConfirmedStockUnits({sourceId,quantity});assert.equal(row.importUnit,unit);assert.equal(validateStockBaseQuantity(convertStock(quantity,row.conversion),row.baseUnit),expected);}
 const domal=applyConfirmedStockUnits({sourceId:'dba29746-fdbe-4dca-91c7-89898ab7f8d5',quantity:'10.15384615'});assert.equal(convertStock(domal.quantity,domal.conversion),'253.84615375');assert.throws(()=>validateStockBaseQuantity(convertStock(domal.quantity,domal.conversion),domal.baseUnit),/fractional/);assert.equal(validateStockBaseQuantity('2.75','KG'),'2.75');
});
test('backend accepts bori, rejects fractional PCS before writing and permits exact corrected counts',()=>{
 const b=accountBackend();opening(b,[item({secondaryUnit:'BORI',conversion:'200',quantity:'4.09',importUnit:'BORI',saleRateUnit:'PCS',purchaseRateUnit:'BORI'})]);assert.equal(read(b).items[0].balance,'818');
 const bad=accountBackend(),payload={id:openingId,openingDate:'2026-10-01',items:[item({secondaryUnit:'PACKET',conversion:'25',quantity:'10.15384615',importUnit:'PACKET',saleRateUnit:'PCS',purchaseRateUnit:'PACKET'})]};assert.equal(bad.post('importStock',payload).ok,false);assert.equal(read(bad).items.length,0);assert.equal(read(bad).movements.length,0);assert.equal(bad.post('importStock',{...payload,items:[{...payload.items[0],quantity:'10'}]}).ok,true);assert.equal(read(bad).items[0].balance,'250');
});

test('confirmed group rules fill doors, sheets and price units but preserve hardware and explicit choices',async()=>{
 const {applyConfirmedStockUnits}=await import('../src/stockImportProfile.js');
 for(const name of ['PVC DOOR','YASH PVC DOOR','WPVC DOOR (27 X 78)','RACK FLUSH DOOR']){const row=applyConfirmedStockUnits({name,baseUnit:'',importUnit:''});assert.equal(row.baseUnit,'NOS');assert.equal(row.saleRateUnit,'NOS');assert.equal(row.purchaseRateUnit,'NOS');}
 for(const name of ['ACP SHEET BLACK 4 X 10','APP SHEET 3 X 9','ATLAS HPL 8 X 4','MDF SHEET','PLYWOOD','PLYBOARD','BLOCK BOARD 35MM'])assert.equal(applyConfirmedStockUnits({name}).baseUnit,'SHEET');
 for(const name of ['PVC DOOR HINGES','MINI DOOR KIT','MDF GLUE','DOOR FRAME','SCREW','WALL FRAME LABOUR'])assert.equal(applyConfirmedStockUnits({name}).baseUnit,undefined);
 const explicit={name:'PVC DOOR',baseUnit:'PCS',importUnit:'PCS',saleRateUnit:'BOX',purchaseRateUnit:'PCS'};assert.deepEqual(applyConfirmedStockUnits(explicit),explicit);
});
test('secondary-unit edits preserve stock balance, identity and original movement conversions',()=>{
 const b=accountBackend();opening(b);const existing=read(b).items[0],payload={id:'stock-settings-edit-000001',_expectedRevision:0,item:{...existing,secondaryUnit:'PACKET',conversion:'100',saleRateUnit:'PCS',purchaseRateUnit:'PACKET'}};
 const result=b.post('updateStockItem',payload);assert.equal(result.ok,true,result.error);assert.equal(result.stock.items[0].balance,'6988');assert.equal(result.stock.items[0].revision,1);assert.equal(result.stock.items[0].secondaryUnit,'PACKET');assert.equal(result.stock.movements[0].conversion,'1000');assert.equal(result.stock.movements[0].unit,'BOX');assert.equal(result.stock.movements[0].baseQuantity,'6988');
 assert.equal(b.post('updateStockItem',payload).ok,true);assert.equal(read(b).items[0].revision,1);assert.equal(b.post('updateStockItem',{...payload,id:'stock-settings-edit-000002'}).ok,false);
 assert.equal(b.post('recordStock',{id:'stock-manual-00000000001',stockItemId:itemId,quantity:'-2',unit:'PACKET',movementDate:'2026-10-05',reason:'Material used'}).ok,true);assert.equal(read(b).items[0].balance,'6788');assert.equal(read(b).movements[1].conversion,'100');
 const reverse={id:'stock-reversal-000000001',reversesId:'stock-manual-00000000001',movementDate:'2026-10-06',reason:'Wrong material'};assert.equal(b.post('reverseStock',reverse).ok,true);assert.equal(read(b).items[0].balance,'6988');
});
test('adding a secondary unit later and interrupted edits leave original stock intact until committed',()=>{
 const b=accountBackend();opening(b,[item({baseUnit:'KG',secondaryUnit:'',conversion:'1',quantity:'25',importUnit:'KG',saleRateUnit:'KG',purchaseRateUnit:'KG'})]);const existing=read(b).items[0];
 const payload={id:'stock-settings-edit-000001',_expectedRevision:0,item:{...existing,secondaryUnit:'GRAM',conversion:'0.001'}};b.failNext('StockOperations');assert.equal(b.post('updateStockItem',payload).ok,false);assert.equal(read(b).items[0].secondaryUnit,'');assert.equal(read(b).items[0].balance,'25');assert.equal(b.post('updateStockItem',payload).ok,true);assert.equal(read(b).items[0].secondaryUnit,'GRAM');assert.equal(read(b).items[0].balance,'25');
 assert.equal(b.post('updateStockItem',{...payload,id:'stock-settings-edit-000002',_expectedRevision:1,item:{...existing,baseUnit:'PCS'}}).ok,false);assert.equal(read(b).items[0].baseUnit,'KG');
});

test('explicit removal of a secondary unit survives import auto-fill',async()=>{
 const {applyConfirmedStockUnits}=await import('../src/stockImportProfile.js');
 const row={sourceId:'b6b6ba7f-cf52-4b3d-b7aa-3bdb03312de6',name:'SCREW',unitsReviewed:true,baseUnit:'PCS',secondaryUnit:'',conversion:'',importUnit:'PCS',saleRateUnit:'PCS',purchaseRateUnit:'PCS'};assert.deepEqual(applyConfirmedStockUnits(row),row);
});

test('as-exported import uses original CSV values and requires no unknown-unit configuration',async()=>{
 const {stockImportItems}=await import('../src/stock.js');
 const rows=parseStockCsv('Item ID,Item Name*,Current stock,Sales Price,Purchase Price,Low stock alert quantity\nunknown-raw,HARDWARE,7.25,20.50,10.25,1\nb6b6ba7f-cf52-4b3d-b7aa-3bdb03312de6,SCREW 13 x 6 SELF,6.988,350,260,1\ngeneric-raw,GENERIC SALE,-612.03,0,0,\n');
 rows[0].quantity='999';rows[0].salePrice='999';const items=stockImportItems(rows,true);assert.equal(items.length,2);assert.equal(items[0].quantity,'7.25');assert.equal(items[0].saleRateMinor,2050);assert.equal(items[0].baseUnit,'UNIT');assert.equal(items[0].saleRateUnit,'UNIT');assert.equal(items[1].quantity,'6.988');assert.equal(items[1].importUnit,'BOX');assert.equal(items[1].saleRateMinor,35000);
 const b=accountBackend(),payload={id:openingId,openingDate:'2026-10-01',importMode:'as-exported',items};const result=b.post('importStock',payload);assert.equal(result.ok,true,result.error);assert.equal(result.stock.items[0].balance,'7.25');assert.equal(result.stock.items[1].balance,'6988');assert.equal(b.post('importStock',payload).ok,true);assert.equal(read(b).items.length,2);assert.equal(b.post('listAccounts',{}).transactions.length,0);
});
test('as-exported preserves inconsistent source fractions exactly while configured imports still reject fractional pieces',()=>{
 const b=accountBackend(),payload={id:openingId,openingDate:'2026-10-01',importMode:'as-exported',items:[item({secondaryUnit:'PACKET',conversion:'25',quantity:'10.15384615',importUnit:'PACKET',saleRateUnit:'PACKET',purchaseRateUnit:'PACKET'})]};const result=b.post('importStock',payload);assert.equal(result.ok,true,result.error);assert.equal(result.stock.items[0].balance,'253.84615375');assert.equal(result.stock.movements[0].quantity,'10.15384615');assert.equal(result.stock.movements[0].unit,'PACKET');assert.equal(result.stock.operations[0].importMode,'as-exported');assert.equal(accountBackend().post('importStock',{...payload,importMode:'configured'}).ok,false);
});
test('CSV unit can be assigned later without changing balances or historical movements',()=>{
 const b=accountBackend();opening(b,[item({baseUnit:'UNIT',secondaryUnit:'',conversion:'1',quantity:'7.25',importUnit:'UNIT',saleRateUnit:'UNIT',purchaseRateUnit:'UNIT'})]);const before=read(b).items[0],payload={id:'stock-settings-edit-000001',_expectedRevision:0,item:{...before,baseUnit:'KG',saleRateUnit:'KG',purchaseRateUnit:'KG',secondaryUnit:'GRAM',conversion:'0.001'}};
 const result=b.post('updateStockItem',payload);assert.equal(result.ok,true,result.error);assert.equal(result.stock.items[0].balance,'7.25');assert.equal(result.stock.items[0].baseUnit,'KG');assert.equal(result.stock.movements[0].baseQuantity,'7.25');assert.equal(result.stock.movements[0].unit,'UNIT');assert.equal(b.post('updateStockItem',payload).ok,true);
 assert.equal(b.post('updateStockItem',{...payload,id:'stock-settings-edit-000002',_expectedRevision:1,item:{...payload.item,baseUnit:'BOX',secondaryUnit:''}}).ok,false);
});
