import {historyInvoices,historyNotes} from './accounts.js';
import {filterTransactions,SHOP_TIMEZONE} from './ledger.js';
const clock=new Intl.DateTimeFormat('en-GB',{timeZone:SHOP_TIMEZONE,hour:'2-digit',minute:'2-digit',second:'2-digit',hourCycle:'h23'});
function recordTime(record){const time=Date.parse(record.createdAt);return Number.isFinite(time)?clock.format(time):'00:00:00';}
export function activityRecords({invoices=[],notes=[],transactions=[],range,category='',method='',query='',kind='all',outbox=[]}){
  const queued=new Map(outbox.map(operation=>[operation.id,operation]));
  const invoiceRows=historyInvoices(invoices,...range,category,query).map(record=>({kind:'invoice',record,date:record.invoiceDate,time:recordTime(record),type:record.type==='sale'?'Sales invoice':'Purchase invoice',category:record.type==='sale'?'Sale':'Purchase',reference:record.invoiceNumber,party:record.partyName,amount:Number(record.totalMinor),status:record._pending?'Pending upload':record.status==='cancelled'?'Cancelled':'Synced'}));
  const noteRows=historyNotes(notes,...range,category,query).map(record=>({kind:'note',record,date:record.noteDate,time:recordTime(record),type:record.type==='credit'?'Credit note':'Debit note',category:record.invoiceType==='sale'?'Sale':'Purchase',reference:record.noteNumber,party:record.partyName,amount:Number(record.amountMinor),status:record._pending?'Pending upload':record.status==='cancelled'?'Cancelled':'Synced'}));
  const payments=filterTransactions(transactions,{start:range[0],end:range[1],category,method,query}).map(record=>{const operation=queued.get(record.id);return {kind:'payment',record,date:record.transactionDate,time:record.transactionTime,type:record.recordType==='transfer'?'Cash/Online exchange':record.recordType==='adjustment'?'Balance adjustment':record.direction==='in'?'Payment received':'Payment made',category:record.category,reference:record.id,party:record.party||record.category,amount:Number(record.amountMinor),status:operation?operation._status==='failed'?'Upload failed':'Pending upload':'Synced',queued:operation};});
  return [...invoiceRows,...noteRows,...payments].filter(row=>kind==='all'||kind===row.kind||kind===row.record.type).sort((a,b)=>`${b.date}T${b.time}`.localeCompare(`${a.date}T${a.time}`)||String(b.record.createdAt||'').localeCompare(String(a.record.createdAt||''))||b.record.id.localeCompare(a.record.id));
}
