import {CUT_UNITS,cuttingDimension} from './cuttingInput.js';
export const PANEL_COLORS=['#c4ddd0','#c8d9f1','#ead8ad','#dfccea','#f1c9b7','#b9dedd','#d9dfb8','#d0d3eb'];
export const escapeCutText=value=>String(value).replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
const dim=(value,unit)=>escapeCutText(cuttingDimension(value,unit));
export function cuttingArea(value){const squareMetres=value/1e14;return squareMetres.toLocaleString('en-IN',squareMetres>0&&squareMetres<1?{maximumSignificantDigits:4}:{maximumFractionDigits:3});}
export function sheetSvg(sheet,unit,{showCuts=true}={}){
 const scale=900/Math.max(sheet.width,sheet.height),width=sheet.width*scale,height=sheet.height*scale;
 const title=`Sheet ${sheet.number}: ${cuttingDimension(sheet.width,unit)} × ${cuttingDimension(sheet.height,unit)} ${unit}`;
 const rect=(row,fill,extra='')=>`<rect x="${row.x*scale}" y="${row.y*scale}" width="${row.width*scale}" height="${row.height*scale}" fill="${fill}" ${extra}/>`;
 const scraps=sheet.leftovers.map(row=>rect(row,'#f4f5f3','stroke="#d3d8d4" stroke-width="0.6"')).join('');
 const panels=sheet.placements.map(panel=>{
  const w=panel.width*scale,h=panel.height*scale,font=Math.min(15,w/10,h/3),cx=(panel.x+panel.width/2)*scale,cy=(panel.y+panel.height/2)*scale;
  const label=`P${panel.id} · ${cuttingDimension(panel.width,unit)} × ${cuttingDimension(panel.height,unit)}${panel.rotated?' ↻':''}`;
  return `<g><title>${escapeCutText(label)}</title>${rect(panel,PANEL_COLORS[(panel.id-1)%PANEL_COLORS.length],'stroke="#536b60" stroke-width="0.8"')}${font>=7?`<text x="${cx}" y="${cy-font*.15}" text-anchor="middle" dominant-baseline="middle" font-size="${font}" fill="#243c33" font-weight="600">P${panel.id}${panel.rotated?' ↻':''}</text><text x="${cx}" y="${cy+font*1.05}" text-anchor="middle" font-size="${font*.85}" fill="#243c33">${dim(panel.width,unit)} × ${dim(panel.height,unit)}</text>`:''}</g>`;
 }).join('');
 const bands=sheet.kerfs.map(row=>rect(row,'#ac6456','opacity=".85"')).join('');
 const cuts=showCuts?sheet.cuts.map(cut=>{const v=cut.axis==='V';return `<line x1="${(v?cut.position:cut.from)*scale}" y1="${(v?cut.from:cut.position)*scale}" x2="${(v?cut.position:cut.to)*scale}" y2="${(v?cut.to:cut.position)*scale}" stroke="#805144" stroke-width="1" stroke-dasharray="5 4"/>`;}).join(''):'';
 return `<svg xmlns="http://www.w3.org/2000/svg" role="img" aria-label="${escapeCutText(title)}" viewBox="-28 -35 ${width+65} ${height+70}" style="width:100%;height:auto;max-height:620px;font-family:Arial,sans-serif"><title>${escapeCutText(title)}</title><text x="${width/2}" y="-14" text-anchor="middle" font-size="15" fill="#486052">${dim(sheet.width,unit)} ${unit}</text><text transform="translate(-13 ${height/2}) rotate(-90)" text-anchor="middle" font-size="15" fill="#486052">${dim(sheet.height,unit)} ${unit}</text><rect width="${width}" height="${height}" fill="#f4f5f3" stroke="#536b60" stroke-width="1.5"/>${scraps}${panels}${bands}${cuts}</svg>`;
}
export function cuttingReportHtml(result,{unit,title='Sheet cutting plan',kerfUnit='mm',createdAt=new Date().toISOString()}={}){
 const sheets=result.sheets.map(sheet=>`<section class="sheet"><h2>Sheet ${sheet.number} · ${dim(sheet.width,unit)} × ${dim(sheet.height,unit)} ${unit}</h2><p>${sheet.placements.length} panels · ${(sheet.panelArea/(sheet.width*sheet.height)*100).toFixed(1)}% material used</p>${sheetSvg(sheet,unit)}<table><thead><tr><th>Panel</th><th>Cut size (${unit})</th><th>Qty</th><th>Rotation</th></tr></thead><tbody>${sheet.placements.map(panel=>`<tr><td>P${panel.id}.${panel.copy}</td><td>${dim(panel.width,unit)} × ${dim(panel.height,unit)}</td><td>1</td><td>${panel.rotated?'90°':'No'}</td></tr>`).join('')}</tbody></table><h3>Cut order · coordinates from the original sheet’s top-left</h3><table><thead><tr><th>Step</th><th>Direction</th><th>Position (${unit})</th><th>Span (${unit})</th></tr></thead><tbody>${sheet.cuts.map(cut=>`<tr><td>${cut.number}</td><td>${cut.axis==='V'?'Vertical · X':'Horizontal · Y'}</td><td>${dim(cut.position,unit)}</td><td>${dim(cut.from,unit)} → ${dim(cut.to,unit)}</td></tr>`).join('')}</tbody></table><p>Leftover pieces (${unit}): ${sheet.leftovers.map(row=>`${dim(row.width,unit)} × ${dim(row.height,unit)}`).join('; ')||'None'}</p></section>`).join('');
 return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${escapeCutText(title)}</title><style>body{font:14px Arial,sans-serif;color:#233c35;max-width:960px;margin:auto;padding:28px}h1{font-size:26px}h2{font-size:19px}p{line-height:1.5}.sheet{margin:24px 0;border-top:1px solid #dbe3dd;padding-top:20px}table{width:100%;border-collapse:collapse;margin:14px 0;font-size:12px}th,td{padding:7px;text-align:left;border-bottom:1px solid #e2e8e3}th{background:#edf4ef}.warning{padding:12px;background:#fff2df}.legend{display:flex;gap:10px;flex-wrap:wrap}.legend span{padding:6px;border-radius:4px}svg{display:block;margin:auto}@page{size:A4 portrait;margin:12mm}@media print{body{padding:0}.sheet{break-before:page}svg{max-height:175mm!important}tr{break-inside:avoid}thead{display:table-header-group}*{print-color-adjust:exact;-webkit-print-color-adjust:exact}}</style></head><body><h1>${escapeCutText(title)}</h1><p>${escapeCutText(new Date(createdAt).toLocaleString())} · Straight cuts · Rotation ${result.rotation?'allowed':'disabled'} · Cutter width ${dim(result.kerf,kerfUnit)} ${kerfUnit} · Goal: ${result.objective==='waste'?'Least waste':'Fewest sheets'}${result.limited?' · Available quantities respected':''}</p><p><strong>${result.sheets.length} sheets · ${result.placed}/${result.requested} panels · ${result.sheetArea?(result.panelArea/result.sheetArea*100).toFixed(1):'0'}% material used</strong><br>Panel area ${cuttingArea(result.panelArea)} m² · Total sheets ${cuttingArea(result.sheetArea)} m² · Leftovers ${cuttingArea(result.unusedArea)} m² · Cutter loss ${cuttingArea(result.kerfArea)} m²</p>${result.unplaced.length?`<p class="warning"><strong>Incomplete plan:</strong> ${result.unplaced.length} panels were not placed in this layout. Do not treat this as a complete cutting list.</p>`:''}<p>Best layout found using several packing attempts; a mathematically optimal layout is not guaranteed. Sizes are finished panel sizes. Cutter loss is included; edge trimming is not. Diagrams are proportional guides, not full-size templates. Verify dimensions and cutting direction before cutting.</p><h2>Requested panels</h2><div class="legend">${result.panels.map(panel=>`<span style="background:${PANEL_COLORS[(panel.id-1)%PANEL_COLORS.length]}">P${panel.id} · ${dim(panel.width,unit)} × ${dim(panel.height,unit)} ${unit} · Qty ${panel.quantity}</span>`).join('')}</div><h2>Available sheet sizes</h2><p>${result.types.map(type=>`${dim(type.width,unit)} × ${dim(type.height,unit)} ${unit}${result.limited?` · Qty ${type.quantity}`:''}`).join('; ')}</p>${result.unplaced.length?`<h2>Unplaced panels</h2><p>${result.unplaced.map(panel=>`P${panel.id}.${panel.copy} · ${dim(panel.width,unit)} × ${dim(panel.height,unit)} ${unit}`).join('; ')}</p>`:''}${sheets}</body></html>`;
}
