import {money,paymentMethodText,transactionIntegrityIssue} from './ledger.js';
import {quantityText,measurementText} from './measurements.js';
import {invoiceNetValue} from './accounts.js';
export const publicBalance=value=>Number.isSafeInteger(value)?`${money(Math.abs(value))}${value>0?' to receive':value<0?' to pay':' · settled'}`:'Unavailable — refresh';
export function invoiceImageDocument(invoice,preferences,{notes=[],partyBalance=null,transactions=[],paymentsConfirmed=false}={}){
 const legacyDiscount=invoice.items.reduce((sum,item)=>sum+Number(item.discountMinor||0),0);
 const linked=transactions.filter(row=>row.id===invoice.paymentId&&row.invoiceId===invoice.id&&!row.deletedAt),payment=paymentsConfirmed&&linked.length===1&&!transactionIntegrityIssue(linked[0])?linked[0]:null;
 const rows=invoice.items.map(item=>[item.description+(item.itemNote?'\n'+item.itemNote:'')+(item.measurements?.length?'\n'+item.measurements.map(row=>measurementText(item,row)).join('\n'):''),quantityText(item),money(item.rateMinor),...(legacyDiscount?[money(item.discountMinor)]:[]),money(item.lineTotalMinor)]);
 return {heading:preferences.shopName,title:invoice.type==='sale'?'Sales invoice':'Purchase invoice',metadata:[...(preferences.printContact?[preferences.address,preferences.phone]:[]),`${invoice.partyName}${invoice.partyPhone?' · '+invoice.partyPhone:''}`,invoice.partyAddress,`Invoice: ${invoice.invoiceNumber} · Date: ${invoice.invoiceDate}`,invoice.challanNumber?`Challan: ${invoice.challanNumber}`:''],columns:legacyDiscount?[['Item',.4],['Quantity',.17],['Rate',.14],['Discount',.14],['Amount',.15]]:[['Item',.5],['Quantity',.18],['Rate',.15],['Amount',.17]],rows,totals:[['Subtotal',money(Number(invoice.totalMinor)+legacyDiscount+Number(invoice.invoiceDiscountMinor||0))],...(legacyDiscount?[['Item discounts included',money(legacyDiscount)]]:[]),['Invoice total',money(invoice.totalMinor)],...(Number(invoice.invoiceDiscountMinor)>0?[['Discount included',money(invoice.invoiceDiscountMinor)]]:[]),...(invoiceNetValue(invoice,notes)!==Number(invoice.totalMinor)?[['After credit/debit notes',money(invoiceNetValue(invoice,notes))]]:[]),...(invoice.walkIn?(payment?[['Paid',money(payment.amountMinor)+' · '+paymentMethodText(payment)],['Pending / credit',money(invoiceNetValue(invoice,notes)-Number(payment.amountMinor))]]:[['Payment status','Unavailable — refresh']]):[['Current party balance',publicBalance(partyBalance)]])],footer:'Amounts in INR · Payments are recorded separately in the party ledger.'};
}
export function ledgerImageDocument({party,statement,range,detailed},preferences){
 const rows=[];for(const entry of statement.entries){rows.push([entry.date,entry.description,entry.delta>0?money(entry.delta):'—',entry.delta<0?money(-entry.delta):'—',publicBalance(entry.balance)]);if(detailed&&entry.invoice){if(!entry.invoice.items)throw new Error('Load invoice details before exporting a detailed ledger.');for(const item of entry.invoice.items)rows.push(['',item.description+' · '+quantityText(item)+(item.measurements?.length?'\n'+item.measurements.map(row=>measurementText(item,row)).join('\n'):'')+' · Item amount: '+money(item.lineTotalMinor),'','','']);}}
 return {heading:preferences.shopName,title:detailed?'Detailed ledger statement':'Ledger statement',metadata:[...(preferences.printContact?[preferences.address,preferences.phone]:[]),party.name,party.phone,`${range[0]} to ${range[1]}`,`Opening balance: ${publicBalance(statement.opening)}`],columns:[['Date',.14],['Particulars',.34],['Debit',.15],['Credit',.15],['Balance',.22]],rows,totals:[['Opening balance',publicBalance(statement.opening)],['Closing balance',publicBalance(statement.closing)]],footer:'Amounts in INR · Debit increases the amount receivable; credit reduces it.'};
}
export function paymentMessage(record,preferences,balance){return [`*${preferences.shopName}*`,record.recordType==='transfer'?'Cash / online exchange':record.recordType==='adjustment'?'Balance adjustment':record.direction==='in'?'*Payment received*':'*Payment made*',record.party||'',`${record.transactionDate} · ${record.category}`,`${money(record.amountMinor)} · ${paymentMethodText(record)}`,Number(record.settlementDiscountMinor)>0?`Settlement discount: ${money(record.settlementDiscountMinor)}`:'',record.partyId?`Party balance: ${publicBalance(balance)}`:''].filter(Boolean).join('\n');}
export function noteMessage(note,preferences,balance){return [`*${preferences.shopName}*`,`*${note.type==='credit'?'Credit':'Debit'} note ${note.noteNumber}*`,note.partyName,`${note.noteDate} · Invoice ${note.invoiceNumber}`,`Amount: ${money(note.amountMinor)}`,note.status==='cancelled'?'CANCELLED — no balance effect':'',note.reason,`Party balance: ${publicBalance(balance)}`].filter(Boolean).join('\n');}
export function receiptImageDocument(title,record,preferences,message){return {heading:preferences.shopName,title,metadata:[record.partyName||record.party||'',record.noteDate||record.transactionDate||''],columns:[['Details',.72],['Amount',.28]],rows:[[message.split('\n').slice(1).join('\n'),money(record.amountMinor)]],totals:[],footer:'Amounts in INR'};}
