import React,{useEffect,useRef,useState} from 'react';
import {documentImages} from './documentImages.js';
export default function DocumentShare({title,message,disabled=false}){
 const [files,setFiles]=useState([]),[urls,setUrls]=useState([]),[busy,setBusy]=useState(false),[feedback,setFeedback]=useState('');const generation=useRef(0);
 useEffect(()=>{generation.current++;setFiles([]);setBusy(false);setFeedback('');return()=>{generation.current++;};},[title,message]);
 useEffect(()=>{const next=files.map(file=>URL.createObjectURL(file));setUrls(next);return()=>next.forEach(url=>URL.revokeObjectURL(url));},[files]);
 async function shareText(){try{if(navigator.share)await navigator.share({title,text:message});else{await navigator.clipboard.writeText(message);setFeedback('Message copied. Paste it into any app.');}}catch(error){if(error.name!=='AbortError')setFeedback('Sharing is unavailable here. Copy the message and paste it into your app.');}}
 async function prepare(){const token=++generation.current;setBusy(true);setFeedback('');try{const next=await documentImages(title,message);if(generation.current===token){setFiles(next);setFeedback(`${next.length} image${next.length===1?'':'s'} ready. Share or download below.`);}}catch(error){if(generation.current===token)setFeedback(error.message);}finally{if(generation.current===token)setBusy(false);}}
 async function shareImages(){try{if(navigator.share&&navigator.canShare?.({files}))await navigator.share({title,files});else setFeedback('File sharing is unavailable in this browser. Download the images below and attach them in any app.');}catch(error){if(error.name!=='AbortError')setFeedback('Use the download links below to attach these images in your app.');}}
 return <section className="document-share-tools"><div className="accounts-controls"><button type="button" data-hotkey="alt+s" aria-keyshortcuts="Alt+S" data-hotkey-label="Share message to an app" className="primary" disabled={disabled||busy} onClick={shareText}>Share message</button><button type="button" data-hotkey="alt+i" aria-keyshortcuts="Alt+I" data-hotkey-label="Prepare document image" className="outline" disabled={disabled||busy} onClick={prepare}>{busy?'Creating images…':'Create image'}</button>{files.length>0&&<button type="button" className="primary" disabled={disabled||busy} onClick={shareImages}>Share image{files.length>1?'s':''}</button>}</div>{files.length>0&&!disabled&&<div className="document-image-preview"><img src={urls[0]} alt={`${title} · first page preview`}/><div>{files.map((file,index)=><a className="outline" key={file.name} href={urls[index]} download={file.name}>Download {files.length>1?`page ${index+1}`:'image'}</a>)}</div></div>}{feedback&&<p className="notice" role="status">{feedback}</p>}<p className="help">Choose an app from your device’s share menu. If unavailable, copy the message or download the images. Long documents use multiple pages.</p></section>;
}
