import React from 'react';
import { categories, methods, money, localNow } from './ledger.js';

export default function PaymentEntry({ editing, cancelEdit, form, update, chooseCategory, save, formRef, amountRef, busy, pending, endpoint, rows, refresh, openHistory, focusAndCenter }) {
  const today = localNow().slice(0,10);
  const recent = rows.filter(t=>t.transactionDate===today).sort((a,b)=>b.transactionTime.localeCompare(a.transactionTime));
  return <section className="pos-layout">
    <form ref={formRef} className="entry-card" onSubmit={save} onFocusCapture={event=>{if(event.target.matches('input,select,textarea,button')) focusAndCenter(event.target);}}>
      {editing && <div className="editing-banner"><span>Editing {editing.transactionDate} · {money(editing.amountMinor)}<small>Your original date is preserved unless you change it.</small></span><button type="button" disabled={busy || !!pending} onClick={cancelEdit}>Cancel edit</button></div>}
      <fieldset disabled={busy || !!pending} className="entry-fields">
        <div className="segmented direction-picker">{['in','out'].map(d=><button data-shortcut={`direction-${d}`} type="button" key={d} aria-pressed={form.direction===d} className={form.direction===d?'chosen':''} onClick={()=>update('direction',d)}>Payment {d} {d==='in'?'↙':'↗'} <kbd>Alt + {d==='in'?'I':'O'}</kbd></button>)}</div>
        <div className="field-caption" id="category-label">Transaction type</div><div className="entry-categories" role="group" aria-labelledby="category-label">{categories.map((c,i)=>{const key={Sale:'S',Purchase:'P',Bhara:'B',Expense:'E'}[c];return <button data-shortcut={`category-${c}`} type="button" key={c} aria-pressed={form.category===c} className={form.category===c?'selected':''} onClick={()=>chooseCategory(c)}><strong>{c}</strong><small>{c==='Bhara'?'Transport & delivery':c==='Sale'?'Customer payments':c==='Purchase'?'Supplier payments':'Everyday costs'}</small><kbd>Alt + {key} · Alt + {i+1}</kbd></button>;})}</div>
        <label className="entry-amount">Amount (₹) <kbd>Alt + Enter</kbd><input id="pos-amount" data-shortcut="amount" ref={amountRef} inputMode="decimal" required type="number" min="0.01" max="1000000000" step="0.01" placeholder="0.00" value={form.amount} onChange={e=>update('amount',e.target.value)}/></label>
        <div className="field-caption" id="method-label">Payment method</div><div className="method-picker" role="group" aria-labelledby="method-label">{methods.map(m=>{const key={Cash:'C',Online:'L',Cheque:''}[m];return <button data-shortcut={key?`method-${m}`:undefined} type="button" key={m} aria-pressed={form.method===m} className={form.method===m?'selected':''} onClick={()=>update('method',m)}>{m}{key&&<> <kbd>Alt + {key}</kbd></>}</button>;})}</div>
        {form.method==='Cheque' && <label>Cheque given date <span className="required">Required</span><input type="date" required value={form.chequeDate} onChange={e=>update('chequeDate',e.target.value)}/></label>}
        <div className="entry-date"><span>{form.customDate ? 'Custom transaction date' : 'Today · time recorded when you save'}</span><button type="button" onClick={()=>update('customDate',!form.customDate)}>{form.customDate?'Use today':'Change date'}</button></div>
        {form.customDate && <label>Transaction date & time<input type="datetime-local" required value={form.dateTime} onChange={e=>update('dateTime',e.target.value)}/></label>}
        <label>Customer / vendor <kbd>Alt + Q</kbd><span>Optional</span><input data-shortcut="vendor" maxLength="150" autoComplete="off" value={form.party} onChange={e=>update('party',e.target.value)} placeholder="Name of person or business"/></label>
        <label>Notes <kbd>Alt + V</kbd><span>Optional</span><textarea data-shortcut="notes" maxLength="1000" rows="2" value={form.notes} onChange={e=>update('notes',e.target.value)} placeholder="What was this payment for?"/></label>
      </fieldset>
      <div className="entry-save"><button data-shortcut="save" className="primary full" disabled={busy || !!pending || !endpoint}>{busy?'Please wait…':pending?'Retry pending payment above':!endpoint?'Connect Sheets to save':editing?'Save changes':'Save payment'} <kbd>Ctrl + Enter</kbd></button><p>{editing?'Updates this payment without creating a duplicate.':'Keep category & payment method for the next entry.'}</p></div>
    </form>
    <aside className="recent-panel"><div className="recent-heading"><div><p className="eyebrow">AT THE COUNTER</p><h2>Today’s payments</h2></div><button aria-label="Refresh recent payments" disabled={busy || !endpoint} onClick={()=>refresh()}>↻</button></div><p className="help">{today} · {recent.length} recorded</p>
      {recent.length ? <ul className="recent-list">{recent.slice(0,8).map(t=><li key={t.id}><div><strong>{t.party || t.category}</strong><small>{t.transactionTime} · {t.category} · {t.method}</small></div><b className={t.direction}>{t.direction==='in'?'+':'−'}{money(t.amountMinor)}</b></li>)}</ul> : <div className="recent-empty">Payments dated today will appear here after saving. Backdated payments are available in History.</div>}
      <button className="outline full" onClick={openHistory}>View transaction history →</button><details className="shortcut-help"><summary>Keyboard shortcuts</summary><p>Alt + N: new entry<br/>Alt + Enter: Amount<br/>Alt + S / P / B / E: Sale / Purchase / Bhara / Expense<br/>Alt + 1–4: Sale / Purchase / Bhara / Expense<br/>Alt + I / O: Payment In / Payment Out<br/>Alt + C / L: Cash / Online<br/>Alt + Q / V: Vendor / Notes<br/>Ctrl + Enter (⌘ + Enter on Mac): save<br/>Tab / Shift + Tab: move between fields</p><p>Pressing a shortcut focuses and centers its field. Escape closes Settings. Shortcuts are paused while Settings is open or a payment is pending.</p></details>
    </aside>
  </section>;
}
