import React,{useEffect,useRef,useState} from 'react';
import {CUT_UNITS,parseCuttingSizes,cuttingLength,cuttingDimension} from './cuttingInput.js';
import {PANEL_COLORS,sheetSvg,cuttingArea,cuttingReportHtml} from './cuttingReport.js';
import {downloadText} from './preferences.js';
import './tools.css';
const initial={panels:'',sheets:'',panelUnit:'in',sheetUnit:'in',kerf:'3',kerfUnit:'mm',rotation:true,objective:'waste',limited:false};
function UnitSelect({label,value,onChange}){return <select aria-label={label} value={value} onChange={event=>onChange(event.target.value)}>{Object.entries(CUT_UNITS).map(([key,unit])=><option key={key} value={key}>{unit.label}</option>)}</select>;}
function SheetDiagram({sheet,unit}){return <div className="cutting-diagram" dangerouslySetInnerHTML={{__html:sheetSvg(sheet,unit)}}/>;}
export default function SheetCuttingPanel({active=true,shopName='Royal Furnitures'}){
 const [input,setInput]=useState(initial),[output,setOutput]=useState(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[exportError,setExportError]=useState(''),[mobileView,setMobileView]=useState('setup'),[sheetIndex,setSheetIndex]=useState(0);
 const signature=JSON.stringify(input),inputsRef=useRef(null),worker=useRef(null),outputRef=useRef(null),printFrame=useRef(null),printTimer=useRef(null);
 const update=(key,value)=>setInput(previous=>({...previous,[key]:value}));
 useEffect(()=>{
  if(!active)return;
  setError('');setExportError('');
  if(outputRef.current?.signature===signature){setBusy(false);return;}
  if(!input.panels.trim()||!input.sheets.trim()){setBusy(false);return;}
  setBusy(true);let cancelled=false;
  const timer=setTimeout(()=>{
   try{
    const panels=parseCuttingSizes(input.panels,input.panelUnit),types=parseCuttingSizes(input.sheets,input.sheetUnit,{sheets:true}),kerf=cuttingLength(input.kerf,input.kerfUnit,{zero:true});
    const job=new Worker(new URL('./cutting.worker.js',import.meta.url),{type:'module'});worker.current=job;
    job.onmessage=event=>{if(cancelled)return;if(event.data.error){setError(event.data.error);}else{const value={result:event.data.result,signature,unit:input.sheetUnit,kerfUnit:input.kerfUnit,createdAt:new Date().toISOString()};outputRef.current=value;setOutput(value);setSheetIndex(0);}setBusy(false);job.terminate();if(worker.current===job)worker.current=null;};
    job.onerror=()=>{if(cancelled)return;setError('Calculation could not finish. Check your sizes or use a smaller batch.');setBusy(false);job.terminate();if(worker.current===job)worker.current=null;};
    job.postMessage({panels,types,kerf,rotation:input.rotation,objective:input.objective,limited:input.limited});
   }catch(cause){setError(cause.message);setBusy(false);}
  },300);
  return()=>{cancelled=true;clearTimeout(timer);worker.current?.terminate();worker.current=null;};
 },[signature,active]);
 useEffect(()=>()=>{clearTimeout(printTimer.current);printFrame.current?.remove();},[]);
 function editInputs(){setMobileView('setup');requestAnimationFrame(()=>{inputsRef.current?.scrollIntoView({behavior:'smooth',block:'start'});inputsRef.current?.querySelector('textarea')?.focus({preventScroll:true});});}
 const current=output?.signature===signature&&!busy&&!error,result=output?.result,unit=output?.unit||input.sheetUnit;
 function report(){return cuttingReportHtml(result,{unit,title:`${shopName} · Sheet cutting plan`,kerfUnit:output.kerfUnit,createdAt:output.createdAt});}
 function download(){try{downloadText(report(),`sheet-cutting-plan-${output.createdAt.slice(0,10)}.html`,'text/html;charset=utf-8');setExportError('');}catch{setExportError('The download could not start. Try Print / Save PDF instead.');}}
 function print(){
  try{
   clearTimeout(printTimer.current);printFrame.current?.remove();const frame=document.createElement('iframe');printFrame.current=frame;frame.title='Print sheet cutting plan';frame.setAttribute('aria-hidden','true');frame.style.cssText='position:fixed;left:-10000px;top:0;width:800px;height:1000px;border:0;';
   const cleanup=()=>{frame.remove();if(printFrame.current===frame)printFrame.current=null;clearTimeout(printTimer.current);};
   frame.onload=()=>{try{frame.contentWindow.addEventListener('afterprint',cleanup,{once:true});frame.contentWindow.focus();frame.contentWindow.print();printTimer.current=setTimeout(cleanup,120000);}catch{cleanup();setExportError('Printing is unavailable here. Download the report and open it in your browser to print.');}};
   frame.srcdoc=report();document.body.append(frame);setExportError('');
  }catch{setExportError('Printing could not start. Download the report instead.');}
 }
 const dim=value=>cuttingDimension(value,unit);
 const selectedIndex=Math.min(sheetIndex,Math.max(0,(result?.sheets.length||0)-1)),selectedSheet=result?.sheets[selectedIndex];
 const usage=new Map();result?.sheets.forEach(sheet=>{const key=`${dim(sheet.width)} × ${dim(sheet.height)} ${unit}`;usage.set(key,(usage.get(key)||0)+1);});
 return <section className="tools-page" aria-label="Sheet cutting" data-mobile-view={mobileView}><div className="heading tools-heading"><div><h2>Sheet cutting</h2><p>Plan your cuts, use less material.</p></div><span className="cutting-live" role="status">{busy?'Calculating…':'Live calculation'}</span></div>
 <div className="cutting-mobile-switch" role="group" aria-label="Cutting workspace"><button aria-pressed={mobileView==='setup'} onClick={editInputs}>Sizes & settings</button><button aria-pressed={mobileView==='plan'} disabled={!result} onClick={()=>setMobileView('plan')}>Cutting plan {result&&<span>{result.sheets.length}</span>}</button></div><div className="cutting-workspace"><aside ref={inputsRef} className="cutting-inputs" aria-label="Cutting sizes and settings"><div className="cutting-editor-heading"><div><span className="cutting-eyebrow">JOB SETUP</span><h2>Sizes & settings</h2></div><span className="cutting-autosave">Auto calculate</span></div><div className="cutting-input-section"><div className="cutting-field-heading"><label htmlFor="cutting-panels"><span className="cutting-step">01</span> Panels <kbd>Alt Q</kbd></label><UnitSelect label="Panel size unit" value={input.panelUnit} onChange={value=>update('panelUnit',value)}/></div><textarea id="cutting-panels" aria-label="Panel sizes" data-hotkey="alt+q" data-hotkey-label="Panel sizes" rows="5" spellCheck="false" placeholder={'24x32x2\n32x32x5\n30x12'} value={input.panels} onChange={event=>update('panels',event.target.value)}/><p className="help">Width × height × quantity. One size per line or separated by commas.</p></div>
 <div className="cutting-input-section"><div className="cutting-field-heading"><label htmlFor="cutting-sheets"><span className="cutting-step">02</span> Sheets <kbd>Alt S</kbd></label><UnitSelect label="Sheet size unit" value={input.sheetUnit} onChange={value=>update('sheetUnit',value)}/></div><textarea id="cutting-sheets" aria-label="Available sheet sizes" data-hotkey="alt+s" data-hotkey-label="Available sheet sizes" rows="3" spellCheck="false" placeholder={input.limited?'48x96x3\n48x120x2':'48x96\n48x120'} value={input.sheets} onChange={event=>update('sheets',event.target.value)}/><label className="cutting-check"><input type="checkbox" checked={input.limited} onChange={event=>update('limited',event.target.checked)}/>Use available quantities</label><p className="help">{input.limited?'Add × quantity after each sheet size; otherwise only 1 sheet of that size is available.':'Unlimited sheets of each size.'}</p></div>
 <div className="cutting-input-section"><label htmlFor="cutting-kerf">Cutter width / kerf <kbd>Alt K</kbd></label><div className="cutting-inline"><input id="cutting-kerf" aria-label="Cutter width" data-hotkey="alt+k" data-hotkey-label="Cutter width" type="text" inputMode="decimal" value={input.kerf} onChange={event=>update('kerf',event.target.value)}/><UnitSelect label="Cutter width unit" value={input.kerfUnit} onChange={value=>update('kerfUnit',value)}/></div><p className="help">1 soot = ⅛ inch · Enter 0 for no cutter loss.</p><label className="cutting-check"><input aria-label="Allow panel rotation" data-hotkey="alt+r" data-hotkey-label="Allow panel rotation" type="checkbox" checked={input.rotation} onChange={event=>update('rotation',event.target.checked)}/>Allow 90° rotation <kbd>Alt R</kbd></label><label htmlFor="cutting-goal">Optimize for</label><select id="cutting-goal" aria-label="Optimization goal" data-hotkey="alt+o" value={input.objective} onChange={event=>update('objective',event.target.value)}><option value="waste">Least material waste</option><option value="sheets">Fewest sheets, then least waste</option></select><details className="cutting-input-help"><summary>Measurement guide</summary><p>Mixed dimensions: <code>2ft 3in 2soot x 4ft x 2</code>. 8 soot = 1 inch; 12 inches = 1 foot. Sizes are finished panel sizes. Straight cuts include cutter loss; edge trimming is not included.</p></details></div>{error&&<p className="cutting-error" role="alert">{error}</p>}<button className="primary cutting-view-plan" disabled={!result||busy||!!error} onClick={()=>{setMobileView('plan');inputsRef.current?.closest('.tools-page')?.scrollIntoView({behavior:'smooth',block:'start'});}}>View cutting plan <span>→</span></button></aside>
 <div className={`cutting-results${result?' has-plan':''}`} aria-label="Cutting plan" role="region" tabIndex={0} aria-busy={busy}>{!result?<div className="cutting-empty"><span aria-hidden="true">▦</span><h2>Your cutting plan appears here</h2><p>Enter panel sizes and available sheets. Diagrams update automatically as you type.</p></div>:<>
 <div className="cutting-toolbar"><div><span className="cutting-eyebrow">RESULTS</span><h2>Cutting plan</h2><p>{current?'Best layout found for this job.':busy?'Updating the layout…':'Inputs changed. The previous result is shown below.'}</p></div><div><button className="outline" data-hotkey="alt+d" disabled={!current} onClick={download}>Download report <kbd>Alt D</kbd></button><button className="primary" data-hotkey="alt+p" disabled={!current} onClick={print}>Print / Save PDF <kbd>Alt P</kbd></button></div></div>
 {exportError&&<p role="alert" className="cutting-error">{exportError}</p>}
 <div className="cutting-metrics">{[['Sheets',result.sheets.length],['Panels fitted',`${result.placed} / ${result.requested}`],['Material used',`${result.sheetArea?(result.panelArea/result.sheetArea*100).toFixed(1):'0'}%`],['Waste incl. cutter',`${cuttingArea(result.sheetArea-result.panelArea)} m²`]].map(([name,value])=><div key={name}><span>{name}</span><strong>{value}</strong></div>)}</div>
 <div className="cutting-summary"><span>Sheets used: {[...usage].map(([size,count])=>`${count} × (${size})`).join(' · ')||'None'}</span><span>Leftovers: {cuttingArea(result.unusedArea)} m² · Cutter loss: {cuttingArea(result.kerfArea)} m²</span></div>
 {result.unplaced.length>0&&<div className="cutting-warning" role="alert"><strong>{result.unplaced.length} panel(s) could not be placed.</strong><p>Add a larger sheet, allow rotation or increase available quantities.</p><ul>{result.panels.filter(panel=>result.unplaced.some(piece=>piece.id===panel.id)).map(panel=><li key={panel.id}>P{panel.id} · {dim(panel.width)} × {dim(panel.height)} {unit} · {result.unplaced.filter(piece=>piece.id===panel.id).length} remaining</li>)}</ul></div>}

 <div className="cutting-sheet-browser"><div className="cutting-browser-heading"><strong>Sheet layouts</strong><span>{selectedSheet?`${selectedIndex+1} of ${result.sheets.length}`:'No sheets used'}</span></div><div className="cutting-sheet-tabs" aria-label="Choose sheet">{result.sheets.map((sheet,index)=><button key={sheet.number} aria-pressed={index===selectedIndex} onClick={()=>setSheetIndex(index)}><span className="cutting-sheet-icon" aria-hidden="true">▯</span><span>Sheet {sheet.number}<small>{dim(sheet.width)} × {dim(sheet.height)} {unit}</small></span></button>)}</div></div>
 <div className="cutting-legend" aria-label="Panel color legend">{result.panels.filter(panel=>selectedSheet?.placements.some(piece=>piece.id===panel.id)).map(panel=><span key={panel.id}><i style={{background:PANEL_COLORS[(panel.id-1)%PANEL_COLORS.length]}}/>P{panel.id} · {dim(panel.width)} × {dim(panel.height)} {unit} · Qty {panel.quantity}</span>)}<span><i className="cutting-scrap-color"/>Leftover</span><span><i className="cutting-kerf-color"/>Cutter loss / cut line</span></div>
 <div className="cutting-sheets">{(selectedSheet?[selectedSheet]:[]).map(sheet=><article className="cutting-sheet" key={sheet.number}><div className="cutting-sheet-heading"><h3>Sheet {sheet.number} <span>{dim(sheet.width)} × {dim(sheet.height)} {unit}</span></h3><span>{sheet.placements.length} panels · {(sheet.panelArea/(sheet.width*sheet.height)*100).toFixed(1)}% used</span></div><SheetDiagram sheet={sheet} unit={unit}/><details className="cutting-details"><summary>Panels, cut order & leftover pieces</summary><div className="cutting-table-scroll"><table><thead><tr><th>Panel</th><th>Cut size ({unit})</th><th>Rotation</th></tr></thead><tbody>{sheet.placements.map(panel=><tr key={panel.pieceId}><td>P{panel.id}.{panel.copy}</td><td>{dim(panel.width)} × {dim(panel.height)}</td><td>{panel.rotated?'90°':'—'}</td></tr>)}</tbody></table><h4>Cut order · coordinates from the original sheet’s top-left</h4><table><thead><tr><th>Step</th><th>Direction</th><th>Position ({unit})</th><th>Span ({unit})</th></tr></thead><tbody>{sheet.cuts.map(cut=><tr key={cut.number}><td>{cut.number}</td><td>{cut.axis==='V'?'Vertical · X':'Horizontal · Y'}</td><td>{dim(cut.position)}</td><td>{dim(cut.from)} → {dim(cut.to)}</td></tr>)}</tbody></table></div><p>Leftovers ({unit}): {sheet.leftovers.map(row=>`${dim(row.width)} × ${dim(row.height)}`).join(' · ')||'None'}</p></details></article>)}</div>
 <p className="cutting-footnote">Best result across {result.trials} packing attempts; an exact minimum is not guaranteed. Diagrams are proportional guides, not full-size templates. Check measurements and material direction before cutting.</p>
 </>}</div></div></section>;
}
