import {applyConfirmedStockUnits} from './stockImportProfile.js';
import React,{useEffect,useState} from 'react';
import {STOCK_UNITS,parseStockCsv,convertStock,stockDecimal,stockText} from './stock.js';
import {localNow} from './ledger.js';
import AccountDialog from './AccountDialog.jsx';
export function stockPrice(value){const text=String(value||'0').trim();if(!/^\d+(\.\d{1,2})?$/.test(text))throw new Error('Prices must have at most two decimal places.');const [whole,fraction='']=text.split('.');const result=Number(BigInt(whole)*100n+BigInt(fraction.padEnd(2,'0')));if(!Number.isSafeInteger(result)||result>100000000000)throw new Error('Invalid stock price.');return result;}
export function UnitSelect({label,value,onChange,optional=false,units=STOCK_UNITS}){return <label>{label}<select aria-label={label} value={value} onChange={e=>onChange(e.target.value)}><option value="">{optional?'None':'Choose unit'}</option>{units.map(unit=><option key={unit}>{unit}</option>)}</select></label>;}
export default function StockImport({endpoint,stock,onClose}){
 const key=`rf.stock-import:${endpoint}`;
 const [draft,setDraft]=useState(()=>{try{const saved=JSON.parse(localStorage.getItem(key)||'null');return saved?{...saved,rows:saved.rows.map(applyConfirmedStockUnits)}:{date:localNow().slice(0,10),rows:[]};}catch{return {date:localNow().slice(0,10),rows:[]};}}),[query,setQuery]=useState(''),[error,setError]=useState(''),[unitFilter,setUnitFilter]=useState('all'),[bulk,setBulk]=useState({baseUnit:'',secondaryUnit:'',conversion:'',importUnit:'',saleRateUnit:'',purchaseRateUnit:''});
 useEffect(()=>{try{localStorage.setItem(key,JSON.stringify(draft));}catch{setError('Cannot save the import draft in this browser. Keep this window open.');}},[draft,key]);
 const update=(id,values)=>setDraft(previous=>({...previous,rows:previous.rows.map(row=>row.id===id?{...row,...values}:row)}));
 const incomplete=row=>row.include&&(!row.baseUnit||!row.importUnit||row.secondaryUnit&&!row.conversion||!row.saleRateUnit||!row.purchaseRateUnit);
 const pending=draft.rows.filter(incomplete).length;
 const visible=draft.rows.filter(row=>(unitFilter!=='pending'||incomplete(row))&&`${row.name} ${row.code}`.toLowerCase().includes(query.toLowerCase()));
 function applyBulk(){setError('');if(!bulk.baseUnit||!bulk.importUnit||!bulk.saleRateUnit||!bulk.purchaseRateUnit||bulk.secondaryUnit&&!bulk.conversion){setError('Choose every bulk unit and any conversion before applying.');return;}const ids=new Set(visible.filter(row=>row.include).map(row=>row.id));if(!ids.size)return;if(!window.confirm(`Apply these confirmed units to ${ids.size} visible included items?`))return;setDraft(previous=>({...previous,rows:previous.rows.map(row=>ids.has(row.id)?{...row,...bulk}:row)}));}
 async function load(file){if(!file)return;setError('');try{if(file.size>1000000)throw new Error('Choose a CSV smaller than 1 MB.');const rows=parseStockCsv(await file.text());setDraft(previous=>({...previous,rows}));}catch(e){setError(e.message);}}
 async function submit(e){e.preventDefault();setError('');try{
  const included=draft.rows.filter(row=>row.include);
  if(!included.length||pending)throw new Error('Confirm units for every included item first.');
  const items=included.map(row=>{if(row.importUnit!==row.baseUnit&&row.importUnit!==row.secondaryUnit)throw new Error(`Confirm the exported unit for ${row.name}.`);const factor=row.importUnit===row.baseUnit?'1':row.conversion;const quantity=stockText(stockDecimal(row.quantity));convertStock(quantity,factor);return {id:row.id,sourceId:row.sourceId,name:row.name,code:row.code,category:'',baseUnit:row.baseUnit,secondaryUnit:row.secondaryUnit,conversion:row.secondaryUnit?row.conversion:'1',importUnit:row.importUnit,quantity,lowStock:row.lowStock===''?'':convertStock(row.lowStock,factor),saleRateUnit:row.saleRateUnit,purchaseRateUnit:row.purchaseRateUnit,saleRateMinor:stockPrice(row.salePrice),purchaseRateMinor:stockPrice(row.purchasePrice)};});
  if(!window.confirm(`Import opening stock for ${items.length} items on ${draft.date}? This does not create purchases or payments.`))return;
  if(await stock.save('importStock',{id:crypto.randomUUID(),openingDate:draft.date,items})){localStorage.removeItem(key);onClose();}
 }catch(e){setError(e.message);}}
 return <AccountDialog title="Import opening stock" className="stock-import-dialog" busy={stock.busy} onClose={onClose}><form data-shortcut-form onSubmit={submit}>
 <p className="help">Your MyBillBook quantities need confirmed units. GENERIC SALE is excluded. Different model codes stay separate. Low-stock thresholds use the exported unit and are converted to the base unit.</p>
 <div className="stock-form-grid"><label>MyBillBook CSV<input type="file" accept=".csv,text/csv" disabled={stock.busy||!!stock.pending} onChange={e=>load(e.target.files[0])}/></label><label>Opening-stock date<input aria-label="Opening-stock date" type="date" required value={draft.date} disabled={stock.busy} onChange={e=>setDraft({...draft,date:e.target.value})}/></label><label>Find item<input type="search" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Name or model code"/></label><label>Show<select value={unitFilter} onChange={e=>setUnitFilter(e.target.value)}><option value="all">All items</option><option value="pending">Units awaiting confirmation</option></select></label></div>
 <details className="stock-bulk"><summary>Apply confirmed units to the filtered items</summary><div className="stock-form-grid"><UnitSelect label="Bulk base unit" value={bulk.baseUnit} onChange={baseUnit=>setBulk({...bulk,baseUnit,secondaryUnit:'',conversion:'',importUnit:'',saleRateUnit:'',purchaseRateUnit:''})}/><UnitSelect label="Bulk secondary unit" optional units={STOCK_UNITS.filter(unit=>unit!==bulk.baseUnit)} value={bulk.secondaryUnit} onChange={secondaryUnit=>setBulk({...bulk,secondaryUnit,conversion:''})}/>{bulk.secondaryUnit&&<label>Base units per secondary unit<input inputMode="decimal" value={bulk.conversion} onChange={e=>setBulk({...bulk,conversion:e.target.value})}/></label>}{[['importUnit','Bulk CSV quantity unit'],['saleRateUnit','Bulk sale price unit'],['purchaseRateUnit','Bulk purchase price unit']].map(([key,title])=><UnitSelect key={key} label={title} units={[bulk.baseUnit,bulk.secondaryUnit].filter(Boolean)} value={bulk[key]} onChange={value=>setBulk({...bulk,[key]:value})}/>)}</div><button type="button" className="outline" disabled={stock.busy||!!stock.pending} onClick={applyBulk}>Apply to visible included items</button></details>
 <p role="status">{draft.rows.length} entries · {draft.rows.filter(row=>row.include).length} included · {pending} awaiting units</p>
 <div className="stock-import-list">{visible.map(row=><fieldset className="stock-import-row" key={row.id} disabled={stock.busy||!!stock.pending}><legend>{row.name}{row.code?` · ${row.code}`:''}</legend><label className="stock-check"><input type="checkbox" checked={row.include} disabled={row.name==='GENERIC SALE'} onChange={e=>update(row.id,{include:e.target.checked})}/>Include in stock</label>{row.include&&<><div className="stock-form-grid"><label>CSV quantity<input aria-label={`Quantity ${row.name} ${row.code}`} value={row.quantity} inputMode="decimal" onChange={e=>update(row.id,{quantity:e.target.value})}/></label><UnitSelect label={`Base unit ${row.name} ${row.code}`} value={row.baseUnit} onChange={baseUnit=>update(row.id,{baseUnit,importUnit:row.importUnit||baseUnit,secondaryUnit:row.secondaryUnit===baseUnit?'':row.secondaryUnit})}/><UnitSelect label={`Secondary unit ${row.name} ${row.code}`} optional units={STOCK_UNITS.filter(unit=>unit!==row.baseUnit)} value={row.secondaryUnit} onChange={secondaryUnit=>update(row.id,{secondaryUnit,conversion:'',importUnit:row.importUnit===row.secondaryUnit?row.baseUnit:row.importUnit})}/>{row.secondaryUnit&&<label>1 {row.secondaryUnit} contains ({row.baseUnit||'base units'})<input aria-label={`Conversion ${row.name} ${row.code}`} value={row.conversion} inputMode="decimal" onChange={e=>update(row.id,{conversion:e.target.value})}/></label>}<UnitSelect label={`CSV quantity unit ${row.name} ${row.code}`} units={[row.baseUnit,row.secondaryUnit].filter(Boolean)} value={row.importUnit} onChange={importUnit=>update(row.id,{importUnit})}/><label>Low-stock threshold (CSV unit)<input value={row.lowStock} inputMode="decimal" onChange={e=>update(row.id,{lowStock:e.target.value})}/></label></div><div className="stock-form-grid"><UnitSelect label={`Sale price unit ${row.name} ${row.code}`} units={[row.baseUnit,row.secondaryUnit].filter(Boolean)} value={row.saleRateUnit} onChange={saleRateUnit=>update(row.id,{saleRateUnit})}/><UnitSelect label={`Purchase price unit ${row.name} ${row.code}`} units={[row.baseUnit,row.secondaryUnit].filter(Boolean)} value={row.purchaseRateUnit} onChange={purchaseRateUnit=>update(row.id,{purchaseRateUnit})}/></div><small>Sale ₹{row.salePrice} · Purchase ₹{row.purchasePrice}{row.purchasePrice==='0'?' · Cost not provided':''}</small></>}</fieldset>)}</div>
 {(error||stock.error)&&<p className="error" role="alert">{error||stock.error}</p>}<div className="stock-savebar"><button type="submit" className="primary" disabled={stock.busy||!!stock.pending||pending>0||!draft.rows.length}>{stock.busy?'Saving…':'Import opening stock'}</button><span>Draft kept on this device. Nothing imports until you confirm.</span></div></form></AccountDialog>;
}
