import React, {useEffect,useState} from 'react';
const actionLabel=action=>({createParty:'Party',updateParty:'Party changes',createInvoice:'Invoice',updateInvoice:'Invoice changes',cancelInvoice:'Invoice cancellation',deletePayment:'Payment deletion',deleteInvoice:'Invoice deletion',deleteParty:'Party deletion',createInvoiceNote:'Correction note',cancelInvoiceNote:'Note cancellation',updateInvoiceNote:'Note changes',deleteInvoiceNote:'Note deletion',create:'Payment',update:'Payment changes',delete:'Payment deletion'}[action]||'Saved request');
export default function SyncStatus({endpoint,accounts,outbox,synced,refreshing,readError,onRefresh,onRetryPayment,onReviewAccounts}){
  const [online,setOnline]=useState(()=>navigator.onLine);
  useEffect(()=>{const change=()=>setOnline(navigator.onLine);window.addEventListener('online',change);window.addEventListener('offline',change);return()=>{window.removeEventListener('online',change);window.removeEventListener('offline',change);};},[]);
  if(!endpoint)return null;
  const queued=[...outbox.map(record=>({key:record._queueId||record.id,label:actionLabel(record._action||'create'),name:record.party||'',status:record._status==='failed'?'Needs attention':record._status==='uploading'?'Uploading':'Saved locally',error:record._error,destination:record._endpoint})),...accounts.queue.map((op,index)=>({key:`account-${index}`,label:actionLabel(op.action),name:op.payload?.name||op.payload?.invoiceNumber||'',status:op.failure?'Needs attention':index===0&&accounts.busy?'Uploading':'Saved locally',error:op.failure?.message|| (op.invalid?'The saved queue needs recovery.':''),destination:op.endpoint}))];
  const failed=queued.some(record=>record.error||record.destination!==endpoint);
  const updating=refreshing||accounts.refreshing;
  const uploading=queued.some(record=>record.status==='Uploading');
  const stale=accounts.cached||accounts.error||readError||!synced||!accounts.loaded;
  const title=queued.length?failed?'Saved locally · needs attention':!online?'Saved locally · waiting for connection':uploading?'Uploading to Google Sheets':'Saved locally · waiting to upload':!online?'Offline · showing saved records':updating?'Checking Google Sheets':stale?'Showing saved records · refresh needed':'Synced with Google Sheets';
  return <section className={`sync-status ${failed?'failed':''}`} aria-label="Save and sync status"><div role="status" aria-live="polite"><strong>{title}</strong><small>{queued.length?`${queued.length} pending change(s). Keep this device’s browser data until they sync.`:'Invoices and payments show confirmed data unless marked as pending.'}</small></div><details><summary>{queued.length?'View pending changes':'Sync details'}</summary>{queued.map(record=><div className="sync-queue-row" key={record.key}><strong>{record.label}{record.name&&` · ${record.name}`}</strong><span>{record.status}</span>{record.error&&<p>{record.error}</p>}{record.destination!==endpoint&&<p>Reconnect the original Sheet to upload this record.</p>}</div>)}{accounts.checkedAt&&<p className="help">Account snapshot: {new Date(accounts.checkedAt).toLocaleString()}</p>}{accounts.error&&<p className="error">{accounts.error}</p>}<div className="accounts-controls"><button type="button" className="outline" disabled={updating||accounts.busy} onClick={onRefresh}>Refresh records</button></div></details><div className="accounts-controls">{outbox[0]?._status==='failed'&&<button type="button" className="outline" onClick={onRetryPayment}>Resolve payment upload</button>}{accounts.pending&&!accounts.busy&&<button type="button" className="outline" disabled={accounts.pending.invalid||accounts.pending.endpoint!==endpoint} onClick={accounts.retry}>Retry upload</button>}{accounts.rejected&&<button type="button" className="outline" onClick={onReviewAccounts}>Review rejected upload</button>}</div></section>;
}
