const actionLabel=action=>({createParty:'Party',updateParty:'Party changes',createInvoice:'Invoice',updateInvoice:'Invoice changes',cancelInvoice:'Invoice cancellation',deletePayment:'Payment deletion',deleteInvoice:'Invoice deletion',deleteParty:'Party deletion',createInvoiceNote:'Correction note',cancelInvoiceNote:'Note cancellation',updateInvoiceNote:'Note changes',deleteInvoiceNote:'Note deletion',create:'Payment',update:'Payment changes',delete:'Payment deletion',recordStock:'Stock update',reviewInvoiceStock:'Invoice stock update',adjustInvoiceStock:'Stock correction',updateStockItem:'Stock item changes'}[action]||'Saved request');
export function syncState({endpoint,accounts={},stock={},outbox=[],online=true,synced=false,refreshing=false,readError='',accountsEnabled=true,stockEnabled=false}){
 const queued=[...outbox.map(record=>({key:record._queueId||record.id,label:actionLabel(record._action||'create'),name:record.party||'',status:record._status==='failed'?'Needs attention':record._status==='uploading'?'Uploading':'Saved locally',failed:record._status==='failed',error:record._error,destination:record._endpoint})),...(accounts.queue||[]).map((op,index)=>({key:`account-${index}`,label:actionLabel(op.action),name:op.payload?.name||op.payload?.invoiceNumber||'',status:op.failure||op.invalid?'Needs attention':index===0&&accounts.busy?'Uploading':'Saved locally',failed:!!op.failure||!!op.invalid,error:op.failure?.message||(op.invalid?'The saved queue needs recovery.':''),destination:op.endpoint})),...(stock.queue||[]).map((op,index)=>({key:`stock-${index}`,label:actionLabel(op.action),name:op.payload?.item?.name||'',status:op.failed||op.invalid?'Needs attention':index===0&&stock.busy?'Uploading':'Saved locally',failed:op.failed||op.invalid,error:op.failed?stock.error:op.invalid?'The saved stock queue needs recovery.':'',destination:endpoint}))];
 const errors=[...new Set([readError,accountsEnabled&&accounts.error,stockEnabled&&stock.error].filter(Boolean))];
 const failed=queued.some(row=>row.failed||row.error||row.destination&&row.destination!==endpoint)||errors.length>0;
 const updating=refreshing||accountsEnabled&&accounts.refreshing||stockEnabled&&stock.loading;
 const stale=!synced||accountsEnabled&&(accounts.cached||!accounts.loaded)||stockEnabled&&stock.cached;
 const title=!endpoint?'Not connected':!online?`Offline${queued.length?` · ${queued.length} saved locally`:''}`:failed?'Sync needs attention':queued.length?`Saving ${queued.length} change${queued.length===1?'':'s'}`:updating?'Checking…':stale?'Saved data · refresh needed':'Up to date';
 return {title,queued,errors,failed,updating,tone:!endpoint?'neutral':failed?'error':!online||stale?'warning':queued.length||updating?'working':'success',spinning:!!endpoint&&online&&!failed&&(updating||queued.some(row=>row.status==='Uploading'))};
}
