import React,{useEffect,useRef,useState} from 'react';
import {syncState} from './syncState.js';
import './sync.css';
export default function SyncStatus({endpoint,accounts,stock,outbox,synced,refreshing,readError,cacheSavedAt,accountsEnabled,stockEnabled,onRefresh,onRetryPayment,onReviewAccounts,onReviewStock,onConnect}){
 const [online,setOnline]=useState(()=>navigator.onLine),details=useRef(null);
 useEffect(()=>{const change=()=>setOnline(navigator.onLine);window.addEventListener('online',change);window.addEventListener('offline',change);const outside=event=>{if(details.current?.open&&!details.current.contains(event.target))details.current.open=false;};document.addEventListener('pointerdown',outside);return()=>{window.removeEventListener('online',change);window.removeEventListener('offline',change);document.removeEventListener('pointerdown',outside);};},[]);
 const state=syncState({endpoint,accounts,stock,outbox,synced,refreshing,readError,online,accountsEnabled,stockEnabled});
 const savedAt=accounts.checkedAt||cacheSavedAt;
 return <section className="sync-status" data-state={state.tone} aria-label="Save and sync status"><details ref={details} onKeyDown={event=>{if(event.key==='Escape'){event.preventDefault();event.stopPropagation();details.current.open=false;details.current.querySelector('summary').focus();}}}>
  <summary aria-label={`Sync status: ${state.title}`}><i className={state.spinning?'sync-dot spinning':'sync-dot'} aria-hidden="true"/><span role="status" aria-live="polite" aria-atomic="true">{state.title}</span><span className="sync-chevron" aria-hidden="true">⌄</span></summary>
  <div className="sync-popover"><div className="sync-popover-heading"><strong>Save & sync</strong><button type="button" aria-label="Close sync details" onClick={()=>{details.current.open=false;details.current.querySelector('summary').focus();}}>×</button></div>
   <p className="sync-description">{state.queued.length?`${state.queued.length} change(s) saved on this device. Keep browser data until they sync.`:!online?'Showing saved records while offline.':state.failed?'Your records are kept. Review the issue below.':!endpoint?'Connect Google Sheets to sync your ledger.':'Your records sync automatically with Google Sheets.'}</p>
   {savedAt&&<p className="sync-timestamp">{accounts.cached?'Saved snapshot':'Last confirmed'}: <time dateTime={savedAt}>{new Date(savedAt).toLocaleString()}</time></p>}
   {stockEnabled&&stock.checkedAt&&(stock.cached||stock.error)&&<p className="sync-timestamp">Stock snapshot: <time dateTime={stock.checkedAt}>{new Date(stock.checkedAt).toLocaleString()}</time></p>}
   <div className="sync-popover-content">{state.errors.map(message=><p className="sync-error" key={message}>{message}</p>)}{state.queued.map(row=><div className="sync-queue-row" key={row.key}><strong>{row.label}{row.name&&` · ${row.name}`}</strong><small>{row.status}</small>{row.error&&!state.errors.includes(row.error)&&<p className="sync-error">{row.error}</p>}{row.destination&&row.destination!==endpoint&&<p className="sync-error">Reconnect the original Sheet to upload this record.</p>}</div>)}</div>
   <div className="sync-popover-actions">{endpoint?<button type="button" className="outline" disabled={state.updating||accounts.busy} onClick={onRefresh}>Refresh records</button>:<button type="button" className="primary" onClick={onConnect}>Connect Sheets</button>}{outbox[0]?._status==='failed'&&<button type="button" className="outline" onClick={onRetryPayment}>Resolve payment upload</button>}{accounts.pending&&!accounts.busy&&<button type="button" className="outline" disabled={accounts.pending.invalid||accounts.pending.endpoint!==endpoint} onClick={accounts.retry}>Retry upload</button>}{accounts.rejected&&<button type="button" className="outline" onClick={onReviewAccounts}>Review rejected upload</button>}{stock.pending&&(stock.pending.failed||stock.pending.invalid)&&<button type="button" className="outline" onClick={onReviewStock}>Review stock upload</button>}</div>
  </div>
 </details></section>;
}
